// hsk-data.js (đã làm sạch + bổ sung ví dụ/dịch HSK1+HSK2+HSK3+HSK4+HSK5)
// Cấu trúc: [hanzi, pinyin, meaning, ex_hanzi, ex_pinyin, ex_viet, tu_loai]

const _HSK_RAW = {
  "hsk1": [
    ["最高管理", "zuìgāo guǎnlǐ", "quản lý cấp cao nhất", "公司实行最高管理层负责制。", "Gōngsī shíxíng zuìgāo guǎnlǐcéng fùzé zhì.", "Công ty thực hiện chế độ chịu trách nhiệm của ban quản lý cấp cao nhất.", "Danh từ"],
  ["决策机构", "juécè jīgòu", "cơ quan ra quyết định", "董事会是公司的决策机构。", "Dǒngshìhuì shì gōngsī de juécè jīgòu.", "Hội đồng quản trị là cơ quan ra quyết định của công ty.", "Danh từ"],
  ["董事会", "dǒngshìhuì", "hội đồng quản trị", "董事会定期开会讨论公司的重要问题。", "Dǒngshìhuì dìngqī kāihuì tǎolùn gōngsī de zhòngyào wèntí.", "Hội đồng quản trị họp định kỳ để thảo luận các vấn đề quan trọng của công ty.", "Danh từ"],
  ["总经理办公室", "zǒngjīnglǐ bàngōngshì", "văn phòng tổng giám đốc", "总经理办公室负责公司的日常工作。", "Zǒngjīnglǐ bàngōngshì fùzé gōngsī de rìcháng gōngzuò.", "Văn phòng tổng giám đốc chịu trách nhiệm các công việc thường ngày của công ty.", "Danh từ"],
  ["战略决策", "zhànlüè juécè", "quyết định chiến lược", "公司需要根据市场的变化做出战略决策。", "Gōngsī xūyào gēnjù shìchǎng de biànhuà zuòchū zhànlüè juécè.", "Công ty cần đưa ra quyết định chiến lược dựa trên sự thay đổi của thị trường.", "Danh từ"],
  ["整体管理", "zhěngtǐ guǎnlǐ", "quản lý tổng thể", "总经理负责公司的整体管理工作。", "Zǒngjīnglǐ fùzé gōngsī de zhěngtǐ guǎnlǐ gōngzuò.", "Tổng giám đốc phụ trách công tác quản lý tổng thể của công ty.", "Danh từ"],
  ["跨部门", "kuà bùmén", "liên phòng ban / liên bộ phận", "项目的成功离不开跨部门的合作。", "Xiàngmù de chénggōng lí bù kāi kuà bùmén de hézuò.", "Sự thành công của dự án không thể thiếu sự hợp tác giữa các phòng ban.", "Tính từ/Danh từ"],
  ["协调", "xiétiáo", "điều phối, phối hợp", "各部门需要加强沟通与协调。", "Gè bùmén xūyào jiāqiáng gōutōng yǔ xiétiáo.", "Các phòng ban cần tăng cường giao tiếp và phối hợp với nhau.", "Động từ"],
  ["报到", "bàodào", "báo danh, trình diện", "新员工到行政人事部报到。", "Xīn yuángōng dào xíngzhèng rénshìbù bàodào.", "Nhân viên mới đến phòng nhân sự để báo danh.", "Động từ"],
  ["人事专员", "rénshì zhuānyuán", "chuyên viên nhân sự", "人事专员负责接待新员工。", "Rénshì zhuānyuán fùzé jiēdài xīn yuángōng.", "Chuyên viên nhân sự phụ trách tiếp đón nhân viên mới.", "Danh từ"],
  ["接待", "jiēdài", "tiếp đón", "人事部接待新员工。", "Rénshìbù jiēdài xīn yuángōng.", "Bộ phận nhân sự tiếp đón nhân viên mới.", "Động từ"],
  ["介绍", "jièshào", "giới thiệu", "他们向新员工介绍公司。", "Tāmen xiàng xīn yuángōng jièshào gōngsī.", "Họ giới thiệu về công ty cho nhân viên mới.", "Động từ"],
  ["组织架构", "zǔzhī jiàgòu", "cơ cấu tổ chức", "公司有清晰的组织架构。", "Gōngsī yǒu qīngxī de zǔzhī jiàgòu.", "Công ty có cơ cấu tổ chức rõ ràng.", "Danh từ"],
  ["职能", "zhínéng", "chức năng, nhiệm vụ", "每个部门有不同的职能。", "Měi gè bùmén yǒu bùtóng de zhínéng.", "Mỗi bộ phận có chức năng khác nhau.", "Danh từ"],
  ["负责人", "fùzérén", "người phụ trách", "我想见这个部门的负责人。", "Wǒ xiǎng jiàn zhège bùmén de fùzérén.", "Tôi muốn gặp người phụ trách bộ phận này.", "Danh từ"],
  ["生产计划部", "shēngchǎn jìhuà bù", "bộ phận kế hoạch sản xuất", "我想向生产计划部询问生产计划。", "Wǒ xiǎng xiàng shēngchǎn jìhuà bù xúnwèn shēngchǎn jìhuà.", "Tôi muốn hỏi kế hoạch sản xuất với bộ phận kế hoạch sản xuất.", "Danh từ"],
  ["生产部", "shēngchǎn bù", "bộ phận sản xuất", "生产部负责生产产品。", "Shēngchǎn bù fùzé shēngchǎn chǎnpǐn.", "Bộ phận sản xuất phụ trách việc sản xuất sản phẩm.", "Danh từ"],
  ["制定", "zhìdìng", "xây dựng, soạn thảo", "公司正在制定新计划。", "Gōngsī zhèngzài zhìdìng xīn jìhuà.", "Công ty đang xây dựng kế hoạch mới.", "Động từ"],
  ["生产计划", "shēngchǎn jìhuà", "kế hoạch sản xuất", "我们需要制定详细的生产计划。", "Wǒmen xūyào zhìdìng xiángxì de shēngchǎn jìhuà.", "Chúng tôi cần lập kế hoạch sản xuất chi tiết.", "Danh từ"],
  ["协调", "xiétiáo", "điều phối, phối hợp", "协调物料与进度很重要。", "Xiétiáo wùliào yǔ jìndù hěn zhòngyào.", "Việc phối hợp nguyên liệu và tiến độ rất quan trọng.", "Động từ"],
  ["物料", "wùliào", "nguyên liệu", "缺少物料会影响生产进度。", "Quēshǎo wùliào huì yǐngxiǎng shēngchǎn jìndù.", "Thiếu nguyên liệu sẽ ảnh hưởng đến tiến độ sản xuất.", "Danh từ"],
  ["进度", "jìndù", "tiến độ", "我们需要严格控制生产进度。", "Wǒmen xūyào yángé kòngzhì shēngchǎn jìndù.", "Chúng ta cần kiểm soát chặt chẽ tiến độ sản xuất.", "Danh từ"],
  ["确保", "quèbǎo", "đảm bảo", "确保按时交货是我们的目标。", "Quèbǎo ànshí jiāohuò shì wǒmen de mùbiāo.", "Đảm bảo giao hàng đúng hạn là mục tiêu của chúng tôi.", "Động từ"],
  ["订单", "dìngdān", "đơn hàng", "订单数量比上个月多。", "Dìngdān shùliàng bǐ shàng gè yuè duō.", "Số lượng đơn hàng nhiều hơn tháng trước.", "Danh từ"],
  ["实际生产操作", "shíjì shēngchǎn cāozuò", "thao tác sản xuất thực tế", "他们负责产品的实际生产操作。", "Tāmen fùzé chǎnpǐn de shíjì shēngchǎn cāozuò.", "Họ phụ trách thao tác sản xuất thực tế của sản phẩm.", "Danh từ"],
  ["生产人员管理", "shēngchǎn rényuán guǎnlǐ", "quản lý nhân viên sản xuất", "生产部也负责生产人员管理。", "Shēngchǎn bù yě fùzé shēngchǎn rényuán guǎnlǐ.", "Bộ phận sản xuất cũng phụ trách quản lý nhân viên sản xuất.", "Danh từ"],
  ["技术支持", "jìshù zhīchí", "hỗ trợ kỹ thuật", "技术部提供技术支持。", "Jìshùbù tígōng jìshù zhīchí.", "Bộ phận kỹ thuật cung cấp hỗ trợ kỹ thuật.", "Danh từ"],
  ["工艺改进", "gōngyì gǎijìn", "cải tiến quy trình công nghệ", "我们不断推进工艺改进。", "Wǒmen búduàn tuījìn gōngyì gǎijìn.", "Chúng tôi luôn thúc đẩy cải tiến quy trình công nghệ.", "Danh từ/Động từ"],
  ["工程部", "gōngchéng bù", "bộ phận kỹ thuật / phòng kỹ thuật", "工程部负责技术管理。", "Gōngchéngbù fùzé jìshù guǎnlǐ.", "Bộ phận kỹ thuật chịu trách nhiệm quản lý kỹ thuật.", "Danh từ"],
  ["技术部", "jìshù bù", "bộ phận kỹ thuật / phòng kỹ thuật", "技术问题由技术部处理。", "Jìshù wèntí yóu jìshùbù chǔlǐ.", "Các vấn đề kỹ thuật do bộ phận kỹ thuật xử lý.", "Danh từ"],
  ["图纸管理", "túzhǐ guǎnlǐ", "quản lý bản vẽ", "我们实行严格的图纸管理。", "Wǒmen shíxíng yángé de túzhǐ guǎnlǐ.", "Chúng tôi thực hiện quản lý bản vẽ nghiêm ngặt.", "Danh từ"],
  ["研发部", "yánfā bù", "bộ phận nghiên cứu và phát triển", "研发部负责技术创新。", "Yánfābù fùzé jìshù chuàngxīn.", "Bộ phận nghiên cứu và phát triển phụ trách đổi mới công nghệ.", "Danh từ"],
  ["新产品设计", "xīn chǎnpǐn shèjì", "thiết kế sản phẩm mới", "研发部负责新产品设计。", "Yánfābù fùzé xīn chǎnpǐn shèjì.", "Bộ phận R&D chịu trách nhiệm thiết kế sản phẩm mới.", "Danh từ"],
  ["样品开发", "yàngpǐn kāifā", "phát triển mẫu", "我们在量产前进行样品开发。", "Wǒmen zài liàngchǎn qián jìnxíng yàngpǐn kāifā.", "Chúng tôi tiến hành phát triển mẫu trước khi sản xuất hàng loạt.", "Danh từ/Động từ"],
  ["技术创新", "jìshù chuàngxīn", "đổi mới kỹ thuật", "技术创新是提升竞争力的关键。", "Jìshù chuàngxīn shì tíshēng jìngzhēnglì de guānjiàn.", "Đổi mới kỹ thuật là chìa khóa nâng cao năng lực cạnh tranh.", "Danh từ"],
  ["负责", "fùzé", "phụ trách, chịu trách nhiệm", "他负责公司的技术工作。", "Tā fùzé gōngsī de jìshù gōngzuò.", "Anh ấy phụ trách mảng kỹ thuật của công ty.", "Động từ"],
  ["推进", "tuījìn", "thúc đẩy, đẩy mạnh", "我们将按进度推进项目。", "Wǒmen jiāng àn jìndù tuījìn xiàngmù.", "Chúng tôi sẽ thúc đẩy dự án theo tiến độ.", "Động từ"],
  ["品质部", "pǐnzhì bù", "bộ phận chất lượng", "品质部负责产品质量管理。", "Pǐnzhìbù fùzé chǎnpǐn zhìliàng guǎnlǐ.", "Bộ phận chất lượng chịu trách nhiệm quản lý chất lượng sản phẩm.", "Danh từ"],
  ["QA/QC", "QA/QC", "kiểm soát chất lượng (đảm bảo chất lượng)", "QA/QC确保产品符合客户要求。", "QA/QC quèbǎo chǎnpǐn fúhé kèhù yāoqiú.", "QA/QC đảm bảo sản phẩm đáp ứng yêu cầu của khách hàng.", "Danh từ"],
  ["来料检验", "láiliào jiǎnyàn", "kiểm tra nguyên liệu đầu vào", "我们对所有来料进行检验。", "Wǒmen duì suǒyǒu láiliào jìnxíng jiǎnyàn.", "Chúng tôi kiểm tra tất cả nguyên liệu đầu vào.", "Danh từ"],
  ["制程品质控制", "zhìchéng pǐnzhì kòngzhì", "kiểm soát chất lượng trong quá trình sản xuất", "制程品质控制非常重要。", "Zhìchéng pǐnzhì kòngzhì fēicháng zhòngyào.", "Kiểm soát chất lượng trong quá trình sản xuất là rất quan trọng.", "Danh từ"],
  ["出货检验", "chūhuò jiǎnyàn", "kiểm tra hàng xuất kho", "货物出货前必须进行出货检验。", "Huòwù chūhuò qián bìxū jìnxíng chūhuò jiǎnyàn.", "Hàng hóa phải được kiểm tra trước khi xuất kho.", "Danh từ"],
  ["确保", "quèbǎo", "đảm bảo", "我们确保产品符合客户要求。", "Wǒmen quèbǎo chǎnpǐn fúhé kèhù yāoqiú.", "Chúng tôi đảm bảo sản phẩm đáp ứng yêu cầu của khách hàng.", "Động từ"],
  ["产品", "chǎnpǐn", "sản phẩm", "我们的产品质量稳定。", "Wǒmen de chǎnpǐn zhìliàng wěndìng.", "Sản phẩm của chúng tôi có chất lượng ổn định.", "Danh từ"],
  ["符合", "fúhé", "phù hợp", "产品必须符合国际标准。", "Chǎnpǐn bìxū fúhé guójì biāozhǔn.", "Sản phẩm phải phù hợp với các tiêu chuẩn quốc tế.", "Động từ"],
  ["客户", "kèhù", "khách hàng", "客户的满意是我们的目标。", "Kèhù de mǎnyì shì wǒmen de mùbiāo.", "Sự hài lòng của khách hàng là mục tiêu của chúng tôi.", "Danh từ"],
  ["体系要求", "tǐxì yāoqiú", "yêu cầu hệ thống (tiêu chuẩn hệ thống)", "我们遵守质量管理体系要求。", "Wǒmen zūnshǒu zhìliàng guǎnlǐ tǐxì yāoqiú.", "Chúng tôi tuân thủ các yêu cầu của hệ thống quản lý chất lượng.", "Danh từ"],
  ["采购部", "cǎigòu bù", "bộ phận mua hàng", "采购部负责采购原材料。", "Cǎigòubù fùzé cǎigòu yuáncáiliào.", "Bộ phận mua hàng phụ trách mua nguyên vật liệu.", "Danh từ"],
  ["原材料", "yuáncáiliào", "nguyên vật liệu", "公司需要采购高质量的原材料。", "Gōngsī xūyào cǎigòu gāozhìliàng de yuáncáiliào.", "Công ty cần mua nguyên vật liệu chất lượng cao.", "Danh từ"],
  ["零件", "língjiàn", "linh kiện", "我们从国外进口零件。", "Wǒmen cóng guówài jìnkǒu língjiàn.", "Chúng tôi nhập khẩu linh kiện từ nước ngoài.", "Danh từ"],
  ["采购", "cǎigòu", "mua sắm", "公司进行设备采购。", "Gōngsī jìnxíng shèbèi cǎigòu.", "Công ty tiến hành mua sắm thiết bị.", "Động từ"],
  ["服务", "fúwù", "dịch vụ", "公司为客户提供优质服务。", "Gōngsī wèi kèhù tígōng yōuzhì fúwù.", "Công ty cung cấp dịch vụ tốt cho khách hàng.", "Danh từ"],
  ["仓储", "cāngchǔ", "lưu kho", "这个部门负责货物仓储。", "Zhège bùmén fùzé huòwù cāngchǔ.", "Bộ phận này chịu trách nhiệm lưu kho hàng hóa.", "Danh từ/Động từ"],
  ["物料", "wùliào", "vật liệu", "需要有效管理仓库里的物料。", "Xūyào yǒuxiào guǎnlǐ cāngkù lǐ de wùliào.", "Cần quản lý vật liệu trong kho hiệu quả.", "Danh từ"],
  ["库存管理", "kùcún guǎnlǐ", "quản lý tồn kho", "公司采用现代化的库存管理系统。", "Gōngsī cǎiyòng xiàndàihuà de kùcún guǎnlǐ xìtǒng.", "Công ty áp dụng hệ thống quản lý tồn kho hiện đại.", "Danh từ"],
  ["发货", "fāhuò", "giao hàng", "今天我们会按时发货。", "Jīntiān wǒmen huì ànshí fāhuò.", "Hôm nay chúng tôi sẽ giao hàng đúng hạn.", "Động từ"],
  ["运输安排", "yùnshū ānpái", "sắp xếp vận chuyển", "物流部负责运输安排。", "Wùliúbù fùzé yùnshū ānpái.", "Bộ phận logistics phụ trách sắp xếp vận chuyển.", "Danh từ"],
  ["财务部", "cáiwù bù", "bộ phận tài chính", "财务部管理公司的费用。", "Cáiwùbù guǎnlǐ gōngsī de fèiyòng.", "Bộ phận tài chính quản lý chi phí của công ty.", "Danh từ"],
  ["财务管理", "cáiwù guǎnlǐ", "quản lý tài chính", "公司需要进行有效的财务管理。", "Gōngsī xūyào jìnxíng yǒuxiào de cáiwù guǎnlǐ.", "Công ty cần quản lý tài chính hiệu quả.", "Danh từ"],
  ["成本核算", "chéngběn hésuàn", "tính toán chi phí", "我们进行生产成本核算。", "Wǒmen jìnxíng shēngchǎn chéngběn hésuàn.", "Chúng tôi tiến hành tính toán chi phí sản xuất.", "Danh từ"],
  ["税务", "shuìwù", "thuế vụ", "公司必须遵守税务规定。", "Gōngsī bìxū zūnshǒu shuìwù guīdìng.", "Công ty phải tuân thủ quy định về thuế.", "Danh từ"],
  ["信息技术部", "xìnxī jìshù bù", "bộ phận công nghệ thông tin", "信息技术部管理公司的系统。", "Xìnxī jìshù bù guǎnlǐ gōngsī de xìtǒng.", "Bộ phận CNTT quản lý hệ thống công ty.", "Danh từ"],
  ["系统", "xìtǒng", "hệ thống", "系统需要经常升级。", "Xìtǒng xūyào jīngcháng shēngjí.", "Hệ thống cần được nâng cấp thường xuyên.", "Danh từ"],
  ["网络", "wǎngluò", "mạng", "内部网络必须稳定安全。", "Nèibù wǎngluò bìxū wěndìng ānquán.", "Mạng nội bộ phải ổn định và an toàn.", "Danh từ"],
  ["数据安全", "shùjù ānquán", "an toàn dữ liệu", "公司注重数据安全。", "Gōngsī zhùzhòng shùjù ānquán.", "Công ty chú trọng bảo mật dữ liệu.", "Danh từ"],
  ["负责", "fùzé", "phụ trách", "这个部门主要负责这项工作。", "Zhège bùmén zhǔyào fùzé zhè xiàng gōngzuò.", "Bộ phận này chịu trách nhiệm chính về công việc.", "Động từ"],
  ["管理", "guǎnlǐ", "quản lý", "良好的管理有助于提高工作效率。", "Liánghǎo de guǎnlǐ yǒuzhùyú tígāo gōngzuò xiàolǜ.", "Quản lý tốt giúp nâng cao hiệu quả công việc.", "Động từ/Danh từ"],
  ["设备维修部", "shèbèi wéixiū bù", "bộ phận bảo trì thiết bị", "设备维修部负责维修机器。", "Shèbèi wéixiū bù fùzé wéixiū jīqì.", "Bộ phận bảo trì thiết bị phụ trách sửa chữa máy móc.", "Danh từ"],
  ["设备", "shèbèi", "thiết bị", "设备需要经常保养。", "Shèbèi xūyào jīngcháng bǎoyǎng.", "Thiết bị cần được bảo dưỡng thường xuyên.", "Danh từ"],
  ["保养", "bǎoyǎng", "bảo dưỡng", "设备必须定期保养。", "Shèbèi bìxū dìngqī bǎoyǎng.", "Thiết bị phải được bảo dưỡng định kỳ.", "Động từ"],
  ["维修", "wéixiū", "sửa chữa", "技术员正在维修设备。", "Jìshùyuán zhèngzài wéixiū shèbèi.", "Kỹ thuật viên đang sửa chữa thiết bị.", "Động từ"],
  ["环境健康与安全部", "huánjìng jiànkāng yǔ ānquán bù", "bộ phận môi trường, sức khỏe và an toàn", "环境健康与安全部负责许多重要工作。", "Huánjìng jiànkāng yǔ ānquán bù fùzé xǔduō zhòngyào gōngzuò.", "Bộ phận EHS phụ trách nhiều công việc quan trọng.", "Danh từ"],
  ["安全生产", "ānquán shēngchǎn", "an toàn sản xuất", "公司始终确保安全生产。", "Gōngsī shǐzhōng quèbǎo ānquán shēngchǎn.", "Công ty luôn đảm bảo an toàn sản xuất.", "Danh từ"],
  ["环境保护", "huánjìng bǎohù", "bảo vệ môi trường", "我们注重环境保护。", "Wǒmen zhùzhòng huánjìng bǎohù.", "Chúng tôi chú trọng bảo vệ môi trường.", "Danh từ"],
  ["员工健康管理", "yuángōng jiànkāng guǎnlǐ", "quản lý sức khỏe nhân viên", "公司有员工健康管理计划。", "Gōngsī yǒu yuángōng jiànkāng guǎnlǐ jìhuà.", "Công ty có chương trình quản lý sức khỏe nhân viên.", "Danh từ"],
  ["生产设备", "shēngchǎn shèbèi", "thiết bị sản xuất", "生产设备必须保持良好状态。", "Shēngchǎn shèbèi bìxū bǎochí liánghǎo zhuàngtài.", "Thiết bị sản xuất phải luôn được giữ tốt.", "Danh từ"],
  ["保障", "bǎozhàng", "đảm bảo", "我们保障设备稳定运行。", "Wǒmen bǎozhàng shèbèi wěndìng yùnxíng.", "Chúng tôi đảm bảo thiết bị hoạt động ổn định.", "Động từ"],
  ["工作环境", "gōngzuò huánjìng", "môi trường làm việc", "公司创造安全健康的工作环境。", "Gōngsī chuàngzào ānquán jiànkāng de gōngzuò huánjìng.", "Công ty tạo môi trường làm việc an toàn và lành mạnh.", "Danh từ"],
  ["管理", "guǎnlǐ", "quản lý", "良好的管理有助于提高工作效率。", "Liánghǎo de guǎnlǐ yǒuzhùyú tígāo gōngzuò xiàolǜ.", "Quản lý tốt giúp nâng cao hiệu quả công việc.", "Động từ/Danh từ"]
]
};

const HSK_DATA = Object.fromEntries(Object.entries(_HSK_RAW).map( ([k,v]) => [k, v.map( ([hanzi,pinyin,meaning,ex_hanzi,ex_pinyin,ex_viet,tu_loai]) => ({
    hanzi,
    pinyin,
    meaning,
    ex_hanzi,
    ex_pinyin,
    ex_viet,
    tu_loai
}))]));

if (typeof module !== "undefined")
    module.exports = {
        HSK_DATA
    };
