// hsk-data.js (đã làm sạch + bổ sung ví dụ/dịch HSK1+HSK2+HSK3+HSK4+HSK5)
// Cấu trúc: [hanzi, pinyin, meaning, ex_hanzi, ex_pinyin, ex_viet, tu_loai]

const _HSK_RAW = {
  "hsk1": [
  ["法律", "fǎlǜ", "pháp luật", "他在大学学习法律专业。", "Tā zài dàxué xuéxí fǎlǜ zhuānyè.", "Anh ấy học chuyên ngành pháp luật ở đại học.", "Danh từ"],
  ["俩", "liǎ", "hai (người)", "咱俩是最好的朋友。", "Zán liǎ shì zuì hǎo de péngyou.", "Hai chúng ta là người bạn tốt nhất.", "Số từ"],
  ["印象", "yìnxiàng", "ấn tượng", "他对北京的印象很好。", "Tā duì Běijīng de yìnxiàng hěn hǎo.", "Ấn tượng của anh ấy về Bắc Kinh rất tốt.", "Danh từ"],
  ["深", "shēn", "sâu, sâu sắc", "这本书给我留下了很深的印象。", "Zhè běn shū gěi wǒ liúxià le hěn shēn de yìnxiàng.", "Cuốn sách này đã để lại cho tôi ấn tượng rất sâu sắc.", "Tính từ"],
  ["熟悉", "shúxī", "quen thuộc, hiểu rõ", "我对这里的环境很熟悉。", "Wǒ duì zhèlǐ de huánjìng hěn shúxī.", "Tôi rất quen thuộc với môi trường ở đây.", "Động từ/Tính từ"],
  ["不仅", "bùjǐn", "không những, không chỉ", "他不仅聪明，而且很努力。", "Tā bùjǐn cōngming, érqiě hěn nǔlì.", "Anh ấy không những thông minh mà còn rất chăm chỉ.", "Liên từ"],
  ["性格", "xìnggé", "tính cách", "他们俩的性格完全不同。", "Tāmen liǎ de xìnggé wánquán bùtóng.", "Tính cách của hai người họ hoàn toàn khác nhau.", "Danh từ"],
  ["开玩笑", "kāi wánxiào", "nói đùa, trêu đùa", "别生气，我只是在开玩笑。", "Bié shēngqì, wǒ zhǐshì zài kāi wánxiào.", "Đừng tức giận, tôi chỉ đang nói đùa thôi.", "Động từ"],
  ["从来", "cónglái", "từ trước tới nay", "我从来没去过那个地方。", "Wǒ cónglái méi qù guò nàge dìfang.", "Tôi từ trước tới nay chưa từng đến nơi đó.", "Phó từ"],
  ["最好", "zuìhǎo", "tốt nhất (là)", "外面下雨了，你最好带把伞。", "Wàimiàn xiàyǔ le, nǐ zuìhǎo dài bǎ sǎn.", "Bên ngoài trời mưa rồi, bạn tốt nhất là mang theo ô.", "Phó từ"],
  ["共同", "gòngtóng", "chung, cùng nhau", "我们有很多共同的爱好。", "Wǒmen yǒu hěn duō gòngtóng de àihào.", "Chúng tôi có rất nhiều sở thích chung.", "Tính từ"],
  ["适合", "shìhé", "phù hợp", "这份工作非常适合你。", "Zhè fèn gōngzuò fēicháng shìhé nǐ.", "Công việc này vô cùng phù hợp với bạn.", "Động từ"],
  ["幸福", "xìngfú", "hạnh phúc", "祝你们一家人生活幸福。", "Zhù nǐmen yì jiā rén shēnghuó xìngfú.", "Chúc cả nhà các bạn cuộc sống hạnh phúc.", "Tính từ/Danh từ"],
  ["生活", "shēnghuó", "cuộc sống, sinh sống", "他在上海生活了十年。", "Tā zài Shànghǎi shēnghuó le shí nián.", "Anh ấy đã sinh sống ở Thượng Hải 10 năm.", "Danh từ/Động từ"],
  ["刚", "gāng", "vừa mới", "我刚下班，现在在回家的路上。", "Wǒ gāng xiàbān, xiànzài zài huíjiā de lùshang.", "Tôi vừa mới tan làm, bây giờ đang trên đường về nhà.", "Phó từ"],
  ["浪漫", "làngmàn", "lãng mạn", "她希望有一个浪漫的婚礼。", "Tā xīwàng yǒu yí ge làngmàn de hūnlǐ.", "Cô ấy hy vọng có một hôn lễ lãng mạn.", "Tính từ"],
  ["够", "gòu", "đủ", "这些钱够买一台新电脑了。", "Zhèxiē qián gòu mǎi yì tái xīn diànnǎo le.", "Số tiền này đủ mua một chiếc máy tính mới rồi.", "Động từ/Tính từ"],
  ["缺点", "quēdiǎn", "khuyết điểm", "每个人都有自己的缺点。", "Měi ge rén dōu yǒu zìjǐ de quēdiǎn.", "Mỗi người đều có khuyết điểm của riêng mình.", "Danh từ"],
  ["接受", "jiēshòu", "chấp nhận, tiếp nhận", "我不能接受这个条件。", "Wǒ bù néng jiēshòu zhège tiáojiàn.", "Tôi không thể chấp nhận điều kiện này.", "Động từ"],
  ["羡慕", "xiànmù", "ngưỡng mộ, ghen tị", "我很羡慕他们美好的爱情。", "Wǒ hěn xiànmù tāmen měihǎo de àiqíng.", "Tôi rất ngưỡng mộ tình yêu đẹp của họ.", "Động từ"],
  ["爱情", "àiqíng", "tình yêu", "这是一部关于爱情的电影。", "Zhè shì yí bù guānyú àiqíng de diànyǐng.", "Đây là một bộ phim về tình yêu.", "Danh từ"],
  ["星星", "xīngxing", "ngôi sao", "天上的星星很亮。", "Tiān shàng de xīngxing hěn liàng.", "Những ngôi sao trên trời rất sáng.", "Danh từ"],
  ["即使", "jíshǐ", "cho dù", "即使下雨，我也要去。", "Jíshǐ xiàyǔ, wǒ yě yào qù.", "Cho dù trời mưa, tôi cũng phải đi.", "Liên từ"],
  ["加班", "jiābān", "tăng ca", "最近工作很忙，我每天都要加班。", "Zuìjìn gōngzuò hěn máng, wǒ měitiān dōu yào jiābān.", "Gần đây công việc rất bận, mỗi ngày tôi đều phải tăng ca.", "Động từ"],
  ["亮", "liàng", "sáng, tỏa sáng", "房间里的灯太亮了。", "Fángjiān lǐ de dēng tài liàng le.", "Đèn trong phòng sáng quá.", "Tính từ/Động từ"],
  ["感动", "gǎndòng", "cảm động", "这个故事让他很感动。", "Zhège gùshi ràng tā hěn gǎndòng.", "Câu chuyện này làm anh ấy rất cảm động.", "Động từ"],
  ["自然", "zìrán", "tự nhiên", "你要学会自然地表达自己的想法。", "Nǐ yào xuéhuì zìrán de biǎodá zìjǐ de xiǎngfǎ.", "Bạn phải học cách biểu đạt suy nghĩ của bản thân một cách tự nhiên.", "Danh từ/Tính từ"],
  ["原因", "yuányīn", "nguyên nhân", "你知道他迟到的原因吗？", "Nǐ zhīdào tā chídào de yuányīn ma?", "Bạn có biết nguyên nhân anh ấy đến muộn không?", "Danh từ"],
  ["互相", "hùxiāng", "lẫn nhau", "朋友之间应该互相帮助。", "Péngyou zhījiān yīnggāi hùxiāng bāngzhù.", "Giữa bạn bè nên giúp đỡ lẫn nhau.", "Phó từ"],
  ["吸引", "xīyǐn", "thu hút, hấp dẫn", "这本小说深深地吸引了我。", "Zhè běn xiǎoshuō shēnshēn de xīyǐn le wǒ.", "Cuốn tiểu thuyết này đã thu hút tôi một cách sâu sắc.", "Động từ"],
  ["幽默", "yōumò", "hài hước", "他是一个非常幽默的人。", "Tā shì yí ge fēicháng yōumò de rén.", "Anh ấy là một người vô cùng hài hước.", "Tính từ"],
  ["脾气", "píqi", "tính khí, nóng nảy", "他总是发脾气，大家都不喜欢他。", "Tā zǒngshì fā píqi, dàjiā dōu bù xǐhuan tā.", "Anh ta luôn cáu gắt, mọi người đều không thích anh ta.", "Danh từ"],
  ["参观", "cānguān", "tham quan", "明天我们要去参观一家工厂。", "Míngtiān wǒmen yào qù cānguān yì jiā gōngchǎng.", "Ngày mai chúng ta sẽ đi tham quan một nhà máy.", "Động từ"],
  ["工厂", "gōngchǎng", "nhà máy, công xưởng", "他在这家工厂工作了五年。", "Tā zài zhè jiā gōngchǎng gōngzuò le wǔ nián.", "Anh ấy làm việc ở nhà máy này đã 5 năm.", "Danh từ"],
  ["安静", "ānjìng", "yên tĩnh", "请大家保持安静。", "Qǐng dàjiā bǎochí ānjìng.", "Xin mọi người giữ yên tĩnh.", "Tính từ"],
  ["稳定", "wěndìng", "ổn định", "他的收入现在很稳定。", "Tā de shōurù xiànzài hěn wěndìng.", "Thu nhập của anh ấy hiện tại rất ổn định.", "Tính từ/Động từ"],
  ["成绩", "chéngjì", "thành tích", "你的考试成绩出来了。", "Nǐ de kǎoshì chéngjì chūlái le.", "Thành tích thi của bạn có rồi.", "Danh từ"],
  ["行动", "xíngdòng", "hành động", "我们必须立刻采取行动。", "Wǒmen bìxū lìkè cǎiqǔ xíngdòng.", "Chúng ta phải lập tức hành động.", "Danh từ/Động từ"],
  ["照顾", "zhàogù", "chăm sóc", "我会好好照顾自己的。", "Wǒ huì hǎohǎo zhàogù zìjǐ de.", "Tôi sẽ tự chăm sóc tốt cho bản thân.", "Động từ"],
  ["知识", "zhīshi", "kiến thức", "书本里有丰富的知识。", "Shūběn lǐ yǒu fēngfù de zhīshi.", "Trong sách vở có kiến thức phong phú.", "Danh từ"],
  ["发脾气", "fā píqi", "nổi cáu, tức giận", "他遇到困难就容易发脾气。", "Tā yùdào kùnnan jiù róngyì fā píqi.", "Anh ấy gặp khó khăn là dễ nổi cáu.", "Cụm động từ"]
],
  "hsk2": [
      ["适应", "shìyìng", "thích nghi", "他很快适应了新环境。", "Tā hěn kuài shìyìng le xīn huánjìng.", "Anh ấy đã rất nhanh thích nghi với môi trường mới.", "Động từ"],
      ["交", "jiāo", "kết giao, giao", "在大学里我交了很多好朋友。", "Zài dàxué lǐ wǒ jiāo le hěn duō hǎo péngyou.", "Ở đại học tôi đã kết giao được rất nhiều bạn tốt.", "Động từ"],
      ["平时", "píngshí", "bình thường, ngày thường", "平时他很少出门。", "Píngshí tā hěn shǎo chūmén.", "Ngày thường anh ấy rất ít khi ra ngoài.", "Danh từ"],
      ["逛", "guàng", "dạo phố", "周末我们去逛商场吧。", "Zhōumò wǒmen qù guàng shāngchǎng ba.", "Cuối tuần chúng ta đi dạo trung tâm thương mại đi.", "Động từ"],
      ["短信", "duǎnxìn", "tin nhắn", "请给我发一条短信。", "Qǐng gěi wǒ fā yì tiáo duǎnxìn.", "Xin hãy gửi cho tôi một tin nhắn.", "Danh từ"],
      ["正好", "zhènghǎo", "vừa vặn, đúng lúc", "你来得正好，我们准备吃饭。", "Nǐ lái de zhènghǎo, wǒmen zhǔnbèi chīfàn.", "Bạn đến đúng lúc lắm, chúng tôi đang chuẩn bị ăn cơm.", "Tính từ/Phó từ"],
      ["聚会", "jùhuì", "tụ tập, gặp mặt", "明天晚上我们有一个同学聚会。", "Míngtiān wǎnshang wǒmen yǒu yí ge tóngxué jùhuì.", "Tối mai chúng tôi có một buổi họp lớp.", "Danh từ/Động từ"],
      ["联系", "liánxì", "liên hệ", "大家以后要多联系。", "Dàjiā yǐhòu yào duō liánxì.", "Mọi người sau này phải liên hệ nhiều hơn.", "Động từ"],
      ["差不多", "chàbuduō", "xấp xỉ, gần như", "这两个词的意思差不多。", "Zhè liǎng ge cí de yìsi chàbuduō.", "Ý nghĩa của hai từ này gần giống nhau.", "Tính từ/Phó từ"],
      ["专门", "zhuānmén", "chuyên môn, đặc biệt", "我是专门来看你的。", "Wǒ shì zhuānmén lái kàn nǐ de.", "Tôi đặc biệt đến để thăm bạn.", "Phó từ"],
      ["毕业", "bìyè", "tốt nghiệp", "他明年大学毕业。", "Tā míngnián dàxué bìyè.", "Anh ấy sang năm tốt nghiệp đại học.", "Động từ"],
      ["麻烦", "máfan", "làm phiền, phiền phức", "这件事太麻烦了。", "Zhè jiàn shì tài máfan le.", "Việc này quá phiền phức.", "Tính từ/Động từ"],
      ["好像", "hǎoxiàng", "hình như, có vẻ", "他好像生病了。", "Tā hǎoxiàng shēngbìng le.", "Anh ấy hình như bị ốm rồi.", "Phó từ"],
      ["重新", "chóngxīn", "làm lại từ đầu", "请你重新写一遍。", "Qǐng nǐ chóngxīn xiě yí biàn.", "Xin bạn hãy viết lại một lần nữa.", "Phó từ"],
      ["尽管", "jǐnguǎn", "mặc dù", "尽管下雨，他还是去了。", "Jǐnguǎn xiàyǔ, tā háishì qù le.", "Mặc dù trời mưa, anh ấy vẫn đi.", "Liên từ"],
      ["真正", "zhēnzhèng", "chân chính, thực sự", "他是我真正的朋友。", "Tā shì wǒ zhēnzhèng de péngyou.", "Anh ấy là người bạn thực sự của tôi.", "Tính từ"],
      ["友谊", "yǒuyì", "tình bạn, hữu nghị", "我们的友谊很深厚。", "Wǒmen de yǒuyì hěn shēnhòu.", "Tình bạn của chúng tôi rất sâu đậm.", "Danh từ"],
      ["逛街", "guàngjiē", "dạo phố, mua sắm", "周末我喜欢和朋友去逛街。", "Zhōumò wǒ xǐhuan hé péngyou qù guàngjiē.", "Cuối tuần tôi thích đi dạo phố cùng bạn bè.", "Động từ"],
      ["心情", "xīnqíng", "tâm trạng", "他今天的心情很好。", "Tā jīntiān de xīnqíng hěn hǎo.", "Tâm trạng của anh ấy hôm nay rất tốt.", "Danh từ"],
      ["建议", "jiànyì", "kiến nghị, đề nghị", "我建议你多休息。", "Wǒ jiànyì nǐ duō xiūxi.", "Tôi đề nghị bạn nghỉ ngơi nhiều hơn.", "Động từ/Danh từ"],
      ["计划", "jìhuà", "kế hoạch", "明年的计划你做好了吗？", "Míngnián de jìhuà nǐ zuò hǎo le ma?", "Kế hoạch năm sau bạn đã làm xong chưa?", "Danh từ/Động từ"],
      ["生产", "shēngchǎn", "sản xuất", "这家工厂主要生产手机。", "Zhè jiā gōngchǎng zhǔyào shēngchǎn shǒujī.", "Nhà máy này chủ yếu sản xuất điện thoại.", "Động từ"],
      ["为了", "wèile", "để, vì", "为了身体健康，他每天跑步。", "Wèile shēntǐ jiànkāng, tā měitiān pǎobù.", "Để cơ thể khỏe mạnh, anh ấy chạy bộ mỗi ngày.", "Giới từ"],
      ["确认", "quèrèn", "xác nhận", "请确认一下您的航班信息。", "Qǐng quèrèn yíxià nín de hángbān xìnxī.", "Xin hãy xác nhận lại thông tin chuyến bay của ngài.", "Động từ"],
      ["任务", "rènwu", "nhiệm vụ", "今天的任务必须完成。", "Jīntiān de rènwu bìxū wánchéng.", "Nhiệm vụ hôm nay bắt buộc phải hoàn thành.", "Danh từ"],
      ["负责", "fùzé", "phụ trách, chịu trách nhiệm", "谁负责这个项目？", "Shéi fùzé zhège xiàngmù?", "Ai phụ trách dự án này?", "Động từ/Tính từ"],
      ["机器", "jīqì", "máy móc", "这台机器坏了，需要修理。", "Zhè tái jīqì huài le, xūyào xiūlǐ.", "Cỗ máy này hỏng rồi, cần phải sửa chữa.", "Danh từ"],
      ["讨论", "tǎolùn", "thảo luận", "我们正在讨论这个问题。", "Wǒmen zhèngzài tǎolùn zhège wèntí.", "Chúng tôi đang thảo luận vấn đề này.", "Động từ"],
      ["处理", "chǔlǐ", "xử lý, giải quyết", "这件事情已经处理好了。", "Zhè jiàn shìqing yǐjīng chǔlǐ hǎo le.", "Chuyện này đã được xử lý xong rồi.", "Động từ"],
      ["丰富", "fēngfù", "phong phú", "他有丰富的工作经验。", "Tā yǒu fēngfù de gōngzuò jīngyàn.", "Anh ấy có kinh nghiệm làm việc phong phú.", "Tính từ"],
      ["无聊", "wúliáo", "vô vị, nhàm chán", "这个周末我觉得很无聊。", "Zhège zhōumò wǒ juéde hěn wúliáo.", "Cuối tuần này tôi cảm thấy rất nhàm chán.", "Tính từ"],
      ["讨厌", "tǎoyàn", "ghét", "我讨厌下雨天。", "Wǒ tǎoyàn xiàyǔ tiān.", "Tôi ghét những ngày mưa.", "Động từ"],
      ["却", "què", "lại (biểu thị trái ngược)", "他很聪明，却不努力。", "Tā hěn cōngming, què bù nǔlì.", "Anh ấy rất thông minh, nhưng lại không nỗ lực.", "Phó từ"],
      ["周围", "zhōuwéi", "xung quanh", "学校周围有很多餐厅。", "Xuéxiào zhōuwéi yǒu hěn duō cāntīng.", "Xung quanh trường học có rất nhiều nhà hàng.", "Danh từ"],
      ["交流", "jiāoliú", "giao lưu", "我们需要多交流经验。", "Wǒmen xūyào duō jiāoliú jīngyàn.", "Chúng ta cần giao lưu kinh nghiệm nhiều hơn.", "Động từ"],
      ["理解", "lǐjiě", "hiểu, thấu hiểu", "希望你能理解我的难处。", "Xīwàng nǐ néng lǐjiě wǒ de nánchù.", "Hy vọng bạn có thể hiểu cho cái khó của tôi.", "Động từ"],
      ["镜子", "jìngzi", "cái gương", "她在照镜子。", "Tā zài zhào jìngzi.", "Cô ấy đang soi gương.", "Danh từ"],
      ["而", "ér", "mà, còn (nối 2 vế)", "南方热，而北方冷。", "Nánfāng rè, ér běifāng lěng.", "Miền nam nóng, còn miền bắc lạnh.", "Liên từ"],
      ["当", "dāng", "khi, trong lúc", "当他回来时，我已经睡了。", "Dāng tā huílái shí, wǒ yǐjīng shuì le.", "Khi anh ấy về, tôi đã ngủ rồi.", "Giới từ"],
      ["困难", "kùnnan", "khó khăn", "我们要勇敢面对困难。", "Wǒmen yào yǒnggǎn miànduì kùnnan.", "Chúng ta phải dũng cảm đối mặt với khó khăn.", "Danh từ/Tính từ"],
      ["及时", "jíshí", "kịp thời", "多亏你及时赶到。", "Duō kuī nǐ jíshí gǎndào.", "May nhờ bạn đến kịp thời.", "Tính từ/Phó từ"],
      ["陪", "péi", "đi cùng, bầu bạn", "今晚我陪你去看电影。", "Jīnwǎn wǒ péi nǐ qù kàn diànyǐng.", "Tối nay tôi đi cùng bạn xem phim nhé.", "Động từ"],
      ["积累", "jīlěi", "tích lũy", "我们需要多积累工作经验。", "Wǒmen xūyào duō jīlěi gōngzuò jīngyàn.", "Chúng ta cần tích lũy nhiều kinh nghiệm làm việc.", "Động từ"],
      ["知识", "zhīshi", "kiến thức, tri thức", "阅读能丰富我们的知识。", "Yuèdú néng fēngfù wǒmen de zhīshi.", "Đọc sách có thể làm phong phú kiến thức của chúng ta.", "Danh từ"],
      ["经验", "jīngyàn", "kinh nghiệm", "他在管理方面有丰富的经验。", "Tā zài guǎnlǐ fāngmiàn yǒu fēngfù de jīngyàn.", "Anh ấy có kinh nghiệm phong phú trong lĩnh vực quản lý.", "Danh từ"],
      ["遇到", "yùdào", "gặp, gặp phải", "如果遇到问题，请马上告诉我。", "Rúguǒ yùdào wèntí, qǐng mǎshàng gàosu wǒ.", "Nếu gặp phải vấn đề, xin hãy nói cho tôi biết ngay.", "Động từ"]
    ],
  "hsk3": [
    ["挺", "tǐng", "rất, khá", "这件衣服挺好看的。", "Zhè jiàn yīfu tǐng hǎokàn de.", "Bộ quần áo này khá đẹp.", "Phó từ"],
    ["紧张", "jǐnzhāng", "căng thẳng", "面试前我有点儿紧张。", "Miànshì qián wǒ yǒudiǎnr jǐnzhāng.", "Trước khi phỏng vấn tôi hơi căng thẳng.", "Tính từ"],
    ["信心", "xìnxīn", "lòng tự tin", "我对这次考试很有信心。", "Wǒ duì zhè cì kǎoshì hěn yǒu xìnxīn.", "Tôi rất tự tin về bài thi lần này.", "Danh từ"],
    ["能力", "nénglì", "năng lực", "他的工作能力很强。", "Tā de gōngzuò nénglì hěn qiáng.", "Năng lực làm việc của anh ấy rất mạnh.", "Danh từ"],
    ["招聘", "zhāopìn", "tuyển dụng", "我们公司正在招聘新员工。", "Wǒmen gōngsī zhèngzài zhāopìn xīn yuángōng.", "Công ty chúng tôi đang tuyển dụng nhân viên mới.", "Động từ"],
    ["提供", "tígōng", "cung cấp", "这家酒店提供免费早餐。", "Zhè jiā jiǔdiàn tígōng miǎnfèi zǎocān.", "Khách sạn này cung cấp bữa sáng miễn phí.", "Động từ"],
    ["负责", "fùzé", "phụ trách, chịu trách nhiệm", "谁负责这个项目？", "Shéi fùzé zhège xiàngmù?", "Ai phụ trách dự án này?", "Động từ"],
    ["本来", "běnlái", "vốn dĩ", "我本来想去，可是下雨了。", "Wǒ běnlái xiǎng qù, kěshì xiàyǔ le.", "Tôi vốn dĩ muốn đi, nhưng lại mưa mất rồi.", "Phó từ/Tính từ"],
    ["应聘", "yìngpìn", "ứng tuyển", "我明天去应聘经理助理。", "Wǒ míngtiān qù yìngpìn jīnglǐ zhùlǐ.", "Ngày mai tôi đi ứng tuyển trợ lý giám đốc.", "Động từ"],
    ["材料", "cáiliào", "tài liệu, tư liệu", "请准备好面试需要的材料。", "Qǐng zhǔnbèi hǎo miànshì xūyào de cáiliào.", "Vui lòng chuẩn bị tốt tài liệu cần thiết cho phỏng vấn.", "Danh từ"],
    ["符合", "fúhé", "phù hợp", "他的条件符合我们的要求。", "Tā de tiáojiàn fúhé wǒmen de yāoqiú.", "Điều kiện của anh ấy phù hợp với yêu cầu của chúng tôi.", "Động từ"],
    ["通知", "tōngzhī", "thông báo", "明天下午有个会，请通知大家。", "Míngtiān xiàwǔ yǒu ge huì, qǐng tōngzhī dàjiā.", "Chiều mai có một cuộc họp, xin hãy thông báo cho mọi người.", "Động từ/Danh từ"],
    ["律师", "lǜshī", "luật sư", "他的爸爸是一名律师。", "Tā de bàba shì yì míng lǜshī.", "Bố anh ấy là một luật sư.", "Danh từ"],
    ["专业", "zhuānyè", "chuyên ngành", "你的大学专业是什么？", "Nǐ de dàxué zhuānyè shì shénme?", "Chuyên ngành đại học của bạn là gì?", "Danh từ"],
    ["另外", "lìngwài", "ngoài ra, mặt khác", "我买了一件衣服，另外还买了一双鞋。", "Wǒ mǎi le yí jiàn yīfu, lìngwài hái mǎi le yì shuāng xié.", "Tôi mua một bộ quần áo, ngoài ra còn mua thêm một đôi giày.", "Đại từ/Phó từ"],
    ["收入", "shōurù", "thu nhập", "他的月收入很高。", "Tā de yuè shōurù hěn gāo.", "Thu nhập hàng tháng của anh ấy rất cao.", "Danh từ"],
    ["咱们", "zánmen", "chúng ta (bao gồm cả người nghe)", "咱们一起去吃饭吧。", "Zánmen yìqǐ qù chīfàn ba.", "Chúng ta cùng đi ăn cơm đi.", "Đại từ"],
    ["安排", "ānpái", "sắp xếp", "我已经安排好了明天的行程。", "Wǒ yǐjīng ānpái hǎo le míngtiān de xíngchéng.", "Tôi đã sắp xếp xong lịch trình ngày mai.", "Động từ"],
    ["首先", "shǒuxiān", "đầu tiên", "首先，我们要了解情况。", "Shǒuxiān, wǒmen yào liǎojiě qíngkuàng.", "Đầu tiên, chúng ta phải tìm hiểu tình hình.", "Phó từ"],
    ["正式", "zhèngshì", "chính thức", "这套西装很正式。", "Zhè tào xīzhuāng hěn zhèngshì.", "Bộ âu phục này rất chính thức.", "Tính từ"],
    ["留", "liú", "để lại, lưu lại", "请在这里留下你的电话。", "Qǐng zài zhèlǐ liú xià nǐ de diànhuà.", "Xin hãy để lại số điện thoại của bạn ở đây.", "Động từ"],
    ["其次", "qícì", "thứ hai, tiếp theo", "首先你要努力，其次要有耐心。", "Shǒuxiān nǐ yào nǔlì, qícì yào yǒu nàixīn.", "Đầu tiên bạn phải nỗ lực, tiếp theo phải có sự kiên nhẫn.", "Đại từ"],
    ["诚实", "chéngshí", "trung thực, thành thật", "诚实是一个人最好的品质。", "Chéngshí shì yí ge rén zuì hǎo de pǐnzhì.", "Trung thực là phẩm chất tốt nhất của một người.", "Tính từ"],
    ["改变", "gǎibiàn", "thay đổi", "你改变了我的生活。", "Nǐ gǎibiàn le wǒ de shēnghuó.", "Bạn đã làm thay đổi cuộc sống của tôi.", "Động từ"],
    ["感觉", "gǎnjué", "cảm giác, cảm thấy", "我感觉今天会下雨。", "Wǒ gǎnjué jīntiān huì xiàyǔ.", "Tôi có cảm giác hôm nay sẽ mưa.", "Danh từ/Động từ"],
    ["判断", "pànduàn", "phán đoán", "不要轻易判断别人。", "Bú yào qīngyì pànduàn biérén.", "Đừng dễ dàng phán đoán người khác.", "Động từ/Danh từ"],
    ["顾客", "gùkè", "khách hàng", "我们要为顾客提供最好的服务。", "Wǒmen yào wèi gùkè tígōng zuì hǎo de fúwù.", "Chúng ta phải cung cấp dịch vụ tốt nhất cho khách hàng.", "Danh từ"],
    ["准时", "zhǔnshí", "đúng giờ", "会议准时开始了。", "Huìyì zhǔnshí kāishǐ le.", "Cuộc họp đã bắt đầu đúng giờ.", "Tính từ"],
    ["不管", "bùguǎn", "cho dù, bất kể", "不管有多难，我都要试一试。", "Bùguǎn yǒu duō nán, wǒ dōu yào shì yí shì.", "Cho dù có khó khăn đến đâu, tôi cũng phải thử một chút.", "Liên từ"],
    ["与", "yǔ", "với, và", "这个问题与我无关。", "Zhège wèntí yǔ wǒ wúguān.", "Vấn đề này không liên quan đến tôi.", "Giới từ/Liên từ"],
    ["约会", "yuēhuì", "cuộc hẹn, hẹn hò", "今晚我有一个约会。", "Jīnwǎn wǒ yǒu yí ge yuēhuì.", "Tối nay tôi có một cuộc hẹn.", "Danh từ/Động từ"]
  ],
  "hsk4": [
    ["提", "tí", "nhắc đến, xách", "别提这件事了。", "Bié tí zhè jiàn shì le.", "Đừng nhắc đến chuyện này nữa.", "Động từ"],
    ["以为", "yǐwéi", "tưởng rằng, cho rằng (thường sai lệch với thực tế)", "我以为你已经走了。", "Wǒ yǐwéi nǐ yǐjīng zǒu le.", "Tôi tưởng rằng bạn đã đi rồi.", "Động từ"],
    ["份", "fèn", "phần, bản (lượng từ công việc, báo...)", "他找到了一份好工作。", "Tā zhǎodào le yí fèn hǎo gōngzuò.", "Anh ấy đã tìm được một công việc tốt.", "Lượng từ"],
    ["完全", "wánquán", "hoàn toàn", "我完全同意你的看法。", "Wǒ wánquán tóngyì nǐ de kànfǎ.", "Tôi hoàn toàn đồng ý với cách nhìn của bạn.", "Phó từ/Tính từ"],
    ["赚", "zhuàn", "kiếm tiền", "他做生意赚了很多钱。", "Tā zuò shēngyi zhuàn le hěn duō qián.", "Anh ấy làm ăn kiếm được rất nhiều tiền.", "Động từ"],
    ["调查", "diàochá", "điều tra, khảo sát", "警方正在调查这个案子。", "Jǐngfāng zhèngzài diàochá zhège ànzi.", "Cảnh sát đang điều tra vụ án này.", "Động từ/Danh từ"],
    ["原来", "yuánlái", "hóa ra, vốn dĩ", "原来是你啊！", "Yuánlái shì nǐ a!", "Hóa ra là bạn à!", "Phó từ/Tính từ"],
    ["计划", "jìhuà", "kế hoạch", "明年的计划你做好了吗？", "Míngnián de jìhuà nǐ zuò hǎo le ma?", "Kế hoạch năm sau bạn đã làm xong chưa?", "Danh từ/Động từ"],
    ["提前", "tíqián", "làm trước, sớm hơn", "会议提前结束了。", "Huìyì tíqián jiéshù le.", "Cuộc họp đã kết thúc sớm hơn.", "Động từ"],
    ["保证", "bǎozhèng", "đảm bảo, bảo đảm", "我保证明天一定到。", "Wǒ bǎozhèng míngtiān yídìng dào.", "Tôi đảm bảo ngày mai nhất định đến.", "Động từ"],
    ["提醒", "tíxǐng", "nhắc nhở", "谢谢你提醒我。", "Xièxie nǐ tíxǐng wǒ.", "Cảm ơn bạn đã nhắc nhở tôi.", "Động từ"],
    ["乱", "luàn", "lộn xộn, bừa bãi", "房间里太乱了，快整理一下。", "Fángjiān lǐ tài luàn le, kuài zhěnglǐ yíxià.", "Trong phòng bừa bãi quá, mau dọn dẹp đi.", "Tính từ"],
    ["生意", "shēngyi", "việc làm ăn, buôn bán", "他家的生意做得很大。", "Tā jiā de shēngyi zuò de hěn dà.", "Việc làm ăn của nhà anh ấy rất lớn.", "Danh từ"],
    ["谈", "tán", "nói chuyện, bàn bạc", "我们来谈谈合作的事吧。", "Wǒmen lái tán tan hézuò de shì ba.", "Chúng ta hãy bàn bạc về chuyện hợp tác nhé.", "Động từ"],
    ["并", "bìng", "không hề (nhấn mạnh phủ định)", "我并不认识他。", "Wǒ bìng bú rènshi tā.", "Tôi hoàn toàn không quen anh ta.", "Phó từ"],
    ["积累", "jīlěi", "tích lũy", "工作经验需要慢慢积累。", "Gōngzuò jīngyàn xūyào mànman jīlěi.", "Kinh nghiệm làm việc cần được tích lũy từ từ.", "Động từ"],
    ["经验", "jīngyàn", "kinh nghiệm", "他有丰富的工作经验。", "Tā yǒu fēngfù de gōngzuò jīngyàn.", "Anh ấy có kinh nghiệm làm việc phong phú.", "Danh từ"],
    ["一切", "yíqiè", "tất cả, mọi thứ", "一切都会好起来的。", "Yíqiè dōu huì hǎo qǐlái de.", "Mọi thứ rồi sẽ tốt lên thôi.", "Đại từ"],
    ["按照", "ànzhào", "dựa theo, theo như", "请按照说明书使用。", "Qǐng ànzhào shuōmíngshū shǐyòng.", "Xin hãy sử dụng theo như sách hướng dẫn.", "Giới từ"],
    ["成功", "chénggōng", "thành công", "只要努力，就会成功。", "Zhǐyào nǔlì, jiù huì chénggōng.", "Chỉ cần nỗ lực thì sẽ thành công.", "Động từ/Tính từ/Danh từ"],
    ["顺利", "shùnlì", "thuận lợi", "祝你工作顺利！", "Zhù nǐ gōngzuò shùnlì!", "Chúc bạn công việc thuận lợi!", "Tính từ"],
    ["感谢", "gǎnxiè", "cảm ơn", "非常感谢您的帮助。", "Fēicháng gǎnxiè nín de bāngzhù.", "Vô cùng cảm ơn sự giúp đỡ của ngài.", "Động từ"],
    ["消息", "xiāoxi", "tin tức", "这是一个好消息。", "Zhè shì yí ge hǎo xiāoxi.", "Đây là một tin tức tốt.", "Danh từ"],
    ["按时", "ànshí", "đúng giờ, đúng hạn", "你要按时吃药。", "Nǐ yào ànshí chī yào.", "Bạn phải uống thuốc đúng giờ.", "Phó từ"],
    ["奖金", "jiǎngjīn", "tiền thưởng", "年底公司发了奖金。", "Niándǐ gōngsī fā le jiǎngjīn.", "Cuối năm công ty đã phát tiền thưởng.", "Danh từ"],
    ["工资", "gōngzī", "tiền lương", "这份工作的工资很高。", "Zhè fèn gōngzuò de gōngzī hěn gāo.", "Tiền lương của công việc này rất cao.", "Danh từ"],
    ["方法", "fāngfǎ", "phương pháp", "这种学习方法很有效。", "Zhè zhǒng xuéxí fāngfǎ hěn yǒuxiào.", "Phương pháp học tập này rất hiệu quả.", "Danh từ"],
    ["知识", "zhīshi", "kiến thức", "书本里有很多知识。", "Shūběn lǐ yǒu hěn duō zhīshi.", "Trong sách có rất nhiều kiến thức.", "Danh từ"],
    ["不得不", "bù dé bù", "không thể không", "下大雨了，我不得不待在家里。", "Xià dàyǔ le, wǒ bù dé bù dāi zài jiālǐ.", "Trời mưa to rồi, tôi không thể không ở nhà.", "Phó từ"],
    ["甚至", "shènzhì", "thậm chí", "他太忙了，甚至连吃饭的时间都没有。", "Tā tài máng le, shènzhì lián chīfàn de shíjiān dōu méiyǒu.", "Anh ấy bận quá, thậm chí thời gian ăn cơm cũng không có.", "Phó từ"],
    ["责任", "zérèn", "trách nhiệm", "这是我的责任。", "Zhè shì wǒ de zérèn.", "Đây là trách nhiệm của tôi.", "Danh từ"]
  ],
  "hsk5": [
    ["家具", "jiājù", "đồ nội thất", "我想买一些新家具。", "Wǒ xiǎng mǎi yìxiē xīn jiājù.", "Tôi muốn mua một ít đồ nội thất mới.", "Danh từ"],
    ["沙发", "shāfā", "ghế sofa", "这个沙发很舒服。", "Zhège shāfā hěn shūfu.", "Chiếc sofa này rất thoải mái.", "Danh từ"],
    ["打折", "dǎzhé", "giảm giá", "这家商店在打折。", "Zhè jiā shāngdiàn zài dǎzhé.", "Cửa hàng này đang giảm giá.", "Động từ"],
    ["价格", "jiàgé", "giá cả", "它的价格比较便宜。", "Tā de jiàgé bǐjiào piányi.", "Giá của nó tương đối rẻ.", "Danh từ"],
    ["质量", "zhìliàng", "chất lượng", "这件衣服的质量很好。", "Zhè jiàn yīfu de zhìliàng hěn hǎo.", "Chất lượng của bộ quần áo này rất tốt.", "Danh từ"],
    ["肯定", "kěndìng", "chắc chắn", "他肯定会来的。", "Tā kěndìng huì lái de.", "Anh ấy chắc chắn sẽ đến.", "Phó từ"],
    ["流行", "liúxíng", "thịnh hành, phổ biến", "这首歌现在很流行。", "Zhè shǒu gē xiànzài hěn liúxíng.", "Bài hát này bây giờ rất thịnh hành.", "Tính từ/Động từ"],
    ["顺便", "shùnbiàn", "tiện thể", "你下班顺便买点儿水果吧。", "Nǐ xiàbān shùnbiàn mǎi diǎnr shuǐguǒ ba.", "Bạn tan làm tiện thể mua ít trái cây nhé.", "Phó từ"],
    ["台", "tái", "chiếc, đài (lượng từ dùng cho máy móc)", "我买了一台新电视。", "Wǒ mǎi le yì tái xīn diànshì.", "Tôi mua một chiếc tivi mới.", "Lượng từ"],
    ["光", "guāng", "chỉ, hết sạch", "钱都花光了。", "Qián dōu huā guāng le.", "Tiền tiêu hết sạch rồi.", "Phó từ/Tính từ"],
    ["实在", "shízài", "thực sự, chân thật", "他是一个很实在的人。", "Tā shì yí ge hěn shízài de rén.", "Anh ấy là một người rất chân thật.", "Phó từ/Tính từ"],
    ["制冷", "zhìlěng", "làm lạnh", "这个空调制冷效果很好。", "Zhège kōngtiáo zhìlěng xiàoguǒ hěn hǎo.", "Hiệu quả làm lạnh của chiếc điều hòa này rất tốt.", "Động từ"],
    ["效果", "xiàoguǒ", "hiệu quả", "这种药的效果不错。", "Zhè zhǒng yào de xiàoguǒ búcuò.", "Hiệu quả của loại thuốc này không tồi.", "Danh từ"],
    ["现金", "xiànjīn", "tiền mặt", "我身上没带现金。", "Wǒ shēnshang méi dài xiànjīn.", "Trên người tôi không mang theo tiền mặt.", "Danh từ"],
    ["邀请", "yāoqǐng", "mời", "感谢你的邀请。", "Gǎnxiè nǐ de yāoqǐng.", "Cảm ơn lời mời của bạn.", "Động từ/Danh từ"],
    ["葡萄", "pútao", "nho", "这些葡萄很甜。", "Zhèxiē pútao hěn tián.", "Những quả nho này rất ngọt.", "Danh từ"],
    ["艺术", "yìshù", "nghệ thuật", "他对艺术很感兴趣。", "Tā duì yìshù hěn gǎn xìngqù.", "Anh ấy rất có hứng thú với nghệ thuật.", "Danh từ"],
    ["广告", "guǎnggào", "quảng cáo", "我看到了一则广告。", "Wǒ kàndào le yì zé guǎnggào.", "Tôi đã nhìn thấy một mẩu quảng cáo.", "Danh từ"],
    ["味道", "wèidào", "mùi vị", "这个菜的味道真好。", "Zhège cài de wèidào zhēn hǎo.", "Mùi vị của món này thật ngon.", "Danh từ"],
    ["实际", "shíjì", "thực tế", "要结合实际情况来考虑。", "Yào jiéhé shíjì qíngkuàng lái kǎolǜ.", "Phải kết hợp tình hình thực tế để xem xét.", "Danh từ/Tính từ"],
    ["考虑", "kǎolǜ", "xem xét, suy nghĩ", "我会认真考虑你的建议。", "Wǒ huì rènzhēn kǎolǜ nǐ de jiànyì.", "Tôi sẽ nghiêm túc xem xét đề nghị của bạn.", "Động từ"],
    ["标准", "biāozhǔn", "tiêu chuẩn", "这符合我们的标准。", "Zhè fúhé wǒmen de biāozhǔn.", "Điều này phù hợp với tiêu chuẩn của chúng tôi.", "Danh từ"],
    ["样子", "yàngzi", "dáng vẻ, hình dáng", "这件衣服的样子很特别。", "Zhè jiàn yīfu de yàngzi hěn tèbié.", "Hình dáng của bộ quần áo này rất đặc biệt.", "Danh từ"],
    ["年龄", "niánlíng", "tuổi tác", "您的年龄是多少？", "Nín de niánlíng shì duōshao?", "Tuổi tác của ngài là bao nhiêu?", "Danh từ"],
    ["浪费", "làngfèi", "lãng phí", "不要浪费时间了。", "Búyào làngfèi shíjiān le.", "Đừng lãng phí thời gian nữa.", "Động từ"],
    ["购物", "gòuwù", "mua sắm", "周末我们去购物中心吧。", "Zhōumò wǒmen qù gòuwù zhōngxīn ba.", "Cuối tuần chúng ta đi trung tâm mua sắm nhé.", "Động từ"],
    ["尤其", "yóuqí", "đặc biệt là", "他喜欢运动，尤其是打篮球。", "Tā xǐhuan yùndòng, yóuqí shì dǎ lánqiú.", "Anh ấy thích thể thao, đặc biệt là chơi bóng rổ.", "Phó từ"],
    ["受到", "shòudào", "nhận được, bị", "他受到了大家的表扬。", "Tā shòudào le dàjiā de biǎoyáng.", "Anh ấy đã nhận được sự tuyên dương của mọi người.", "Động từ"],
    ["任何", "rènhé", "bất kỳ", "如果有任何问题，请告诉我。", "Rúguǒ yǒu rènhé wèntí, qǐng gàosu wǒ.", "Nếu có bất kỳ vấn đề gì, xin hãy nói cho tôi biết.", "Đại từ"],
    ["寄", "jì", "gửi (thư, bưu kiện)", "我去邮局寄包裹。", "Wǒ qù yóujú jì bāoguǒ.", "Tôi đi bưu điện gửi bưu kiện.", "Động từ"]
  ],
  "hsk6": [
    ["售货员", "shòuhuòyuán", "nhân viên bán hàng", "她是一名售货员。", "Tā shì yì míng shòuhuòyuán.", "Cô ấy là một nhân viên bán hàng.", "Danh từ"],
    ["袜子", "wàzi", "tất, vớ", "这双袜子很舒服。", "Zhè shuāng wàzi hěn shūfu.", "Đôi tất này rất thoải mái.", "Danh từ"],
    ["打扰", "dǎrǎo", "làm phiền", "对不起，打扰一下。", "Duìbùqǐ, dǎrǎo yíxià.", "Xin lỗi, làm phiền một chút.", "Động từ"],
    ["竟然", "jìngrán", "lại, vậy mà", "他竟然没来。", "Tā jìngrán méi lái.", "Anh ấy vậy mà lại không đến.", "Phó từ"],
    ["西红柿", "xīhóngshì", "cà chua", "我喜欢吃西红柿。", "Wǒ xǐhuan chī xīhóngshì.", "Tôi thích ăn cà chua.", "Danh từ"],
    ["百分之", "bǎifēnzhī", "phần trăm", "百分之八十的人同意了。", "Bǎifēnzhī bāshí de rén tóngyì le.", "80 phần trăm người đã đồng ý.", "Cụm từ"],
    ["倍", "bèi", "lần, gấp bội", "他的工资是我的两倍。", "Tā de gōngzī shì wǒ de liǎng bèi.", "Lương của anh ấy gấp đôi của tôi.", "Lượng từ"],
    ["皮肤", "pífū", "da", "她的皮肤很好。", "Tā de pífū hěn hǎo.", "Da của cô ấy rất đẹp.", "Danh từ"],
    ["好处", "hǎochù", "điểm tốt, lợi ích", "运动对身体有好处。", "Yùndòng duì shēntǐ yǒu hǎochù.", "Vận động có lợi cho cơ thể.", "Danh từ"],
    ["尝", "cháng", "nếm", "你尝尝这个菜。", "Nǐ cháng chang zhège cài.", "Bạn nếm thử món này xem.", "Động từ"],
    ["轻", "qīng", "nhẹ", "这个箱子很轻。", "Zhège xiāngzi hěn qīng.", "Cái rương này rất nhẹ.", "Tính từ"],
    ["方面", "fāngmiàn", "phương diện, mặt", "在这个方面他很有经验。", "Zài zhège fāngmiàn tā hěn yǒu jīngyàn.", "Về mặt này anh ấy rất có kinh nghiệm.", "Danh từ"],
    ["值得", "zhídé", "đáng, xứng đáng", "这本书值得一读。", "Zhè běn shū zhídé yì dú.", "Cuốn sách này đáng để đọc một lần.", "Động từ"],
    ["活动", "huódòng", "hoạt động", "周末你有什么活动？", "Zhōumò nǐ yǒu shénme huódòng?", "Cuối tuần bạn có hoạt động gì?", "Danh từ/Động từ"],
    ["内", "nèi", "trong", "请在三天内完成。", "Qǐng zài sān tiān nèi wánchéng.", "Xin hãy hoàn thành trong vòng ba ngày.", "Danh từ"],
    ["免费", "miǎnfèi", "miễn phí", "这里提供免费早餐。", "Zhèlǐ tígōng miǎnfèi zǎocān.", "Ở đây cung cấp bữa sáng miễn phí.", "Động từ"],
    ["修理", "xiūlǐ", "sửa chữa", "我的自行车需要修理。", "Wǒ de zìxíngchē xūyào xiūlǐ.", "Xe đạp của tôi cần phải sửa chữa.", "Động từ"],
    ["支持", "zhīchí", "ủng hộ", "感谢大家的支持。", "Gǎnxiè dàjiā de zhīchí.", "Cảm ơn sự ủng hộ của mọi người.", "Động từ/Danh từ"],
    ["举行", "jǔxíng", "tổ chức", "会议将在明天举行。", "Huìyì jiāng zài míngtiān jǔxíng.", "Cuộc họp sẽ được tổ chức vào ngày mai.", "Động từ"],
    ["满", "mǎn", "đầy, đủ", "水倒满了。", "Shuǐ dào mǎn le.", "Nước rót đầy rồi.", "Tính từ"],
    ["其中", "qízhōng", "trong đó", "我们班有三十人，其中一半是女生。", "Wǒmen bān yǒu sānshí rén, qízhōng yíbàn shì nǚshēng.", "Lớp chúng tôi có 30 người, trong đó một nửa là nữ.", "Đại từ"],
    ["小说", "xiǎoshuō", "tiểu thuyết", "他喜欢看小说。", "Tā xǐhuan kàn xiǎoshuō.", "Anh ấy thích đọc tiểu thuyết.", "Danh từ"],
    ["会员卡", "huìyuánkǎ", "thẻ hội viên", "你有这家店的会员卡吗？", "Nǐ yǒu zhè jiā diàn de huìyuánkǎ ma?", "Bạn có thẻ hội viên của cửa hàng này không?", "Danh từ"],
    ["所有", "suǒyǒu", "tất cả", "这里所有的书都是我的。", "Zhèlǐ suǒyǒu de shū dōu shì wǒ de.", "Tất cả sách ở đây đều là của tôi.", "Tính từ"],
    ["获得", "huòdé", "giành được, đạt được", "他获得了第一名。", "Tā huòdé le dì yī míng.", "Anh ấy đã giành được giải nhất.", "Động từ"],
    ["情况", "qíngkuàng", "tình hình", "现在的情况很复杂。", "Xiànzài de qíngkuàng hěn fùzá.", "Tình hình bây giờ rất phức tạp.", "Danh từ"],
    ["例如", "lìrú", "ví dụ", "很多水果都很甜，例如苹果、西瓜。", "Hěn duō shuǐguǒ dōu hěn tián, lìrú píngguǒ, xīguā.", "Rất nhiều trái cây rất ngọt, ví dụ như táo, dưa hấu.", "Động từ"],
    ["举办", "jǔbàn", "tổ chức", "学校举办了一次运动会。", "Xuéxiào jǔbàn le yí cì yùndònghuì.", "Trường học đã tổ chức một hội thao.", "Động từ"],
    ["各", "gè", "các, mỗi", "各位旅客请注意。", "Gèwèi lǚkè qǐng zhùyì.", "Xin quý hành khách chú ý.", "Đại từ"],
    ["降低", "jiàngdī", "hạ thấp, giảm", "这里的温度降低了。", "Zhèlǐ de wēndù jiàngdī le.", "Nhiệt độ ở đây đã giảm xuống.", "Động từ"]
  ],
  "hsk7": [
    ["流血", "liú xiě", "chảy máu", "你的手流血了。", "Nǐ de shǒu liú xiě le.", "Tay của bạn chảy máu rồi.", "Động từ"],
    ["擦", "cā", "lau, chùi", "请用纸巾擦一下。", "Qǐng yòng zhǐjīn cā yíxià.", "Vui lòng dùng khăn giấy lau một chút.", "Động từ"],
    ["气候", "qìhòu", "khí hậu", "这里的气候很适合居住。", "Zhèlǐ de qìhòu hěn shìhé jūzhù.", "Khí hậu ở đây rất thích hợp để ở.", "Danh từ"],
    ["估计", "gūjì", "ước lượng, đoán", "我估计他今天不会来了。", "Wǒ gūjì tā jīntiān bú huì lái le.", "Tôi đoán hôm nay anh ấy sẽ không đến.", "Động từ"],
    ["咳嗽", "késou", "ho", "他感冒了，一直咳嗽。", "Tā gǎnmào le, yìzhí késou.", "Anh ấy bị cảm, ho suốt.", "Động từ"],
    ["严重", "yánzhòng", "nghiêm trọng", "他的病很严重。", "Tā de bìng hěn yánzhòng.", "Bệnh của anh ấy rất nghiêm trọng.", "Tính từ"],
    ["窗户", "chuānghu", "cửa sổ", "请把窗户打开。", "Qǐng bǎ chuānghu dǎkāi.", "Vui lòng mở cửa sổ ra.", "Danh từ"],
    ["空气", "kōngqì", "không khí", "早上的空气很新鲜。", "Zǎoshang de kōngqì hěn xīnxiān.", "Không khí buổi sáng rất trong lành.", "Danh từ"],
    ["抽烟", "chōuyān", "hút thuốc", "请不要在这里抽烟。", "Qǐng búyào zài zhèlǐ chōuyān.", "Xin đừng hút thuốc ở đây.", "Động từ"],
    ["动作", "dòngzuò", "động tác", "这个动作很难做。", "Zhège dòngzuò hěn nán zuò.", "Động tác này rất khó làm.", "Danh từ"],
    ["帅", "shuài", "đẹp trai", "他长得很帅。", "Tā zhǎng de hěn shuài.", "Anh ấy trông rất đẹp trai.", "Tính từ"],
    ["出现", "chūxiàn", "xuất hiện", "天上出现了一道彩虹。", "Tiān shàng chūxiàn le yí dào cǎihóng.", "Trên trời xuất hiện một đạo cầu vồng.", "Động từ"],
    ["后悔", "hòuhuǐ", "hối hận", "我后悔没听你的话。", "Wǒ hòuhuǐ méi tīng nǐ de huà.", "Tôi hối hận vì đã không nghe lời bạn.", "Động từ"],
    ["来不及", "láibují", "không kịp", "快点，不然就来不及了。", "Kuài diǎn, bùrán jiù láibují le.", "Nhanh lên, nếu không thì không kịp đâu.", "Động từ"],
    ["反对", "fǎnduì", "phản đối", "我们都反对这个计划。", "Wǒmen dōu fǎnduì zhège jìhuà.", "Chúng tôi đều phản đối kế hoạch này.", "Động từ"],
    ["大夫", "dàifu", "bác sĩ", "大夫说我需要休息。", "Dàifu shuō wǒ xūyào xiūxi.", "Bác sĩ nói tôi cần nghỉ ngơi.", "Danh từ"],
    ["植物", "zhíwù", "thực vật", "院子里种了很多植物。", "Yuànzi lǐ zhòng le hěn duō zhíwù.", "Trong sân trồng rất nhiều thực vật.", "Danh từ"],
    ["研究", "yánjiū", "nghiên cứu", "他在研究中国历史。", "Tā zài yánjiū Zhōngguó lìshǐ.", "Anh ấy đang nghiên cứu lịch sử Trung Quốc.", "Động từ/Danh từ"],
    ["超过", "chāoguò", "vượt qua", "他的成绩超过了我。", "Tā de chéngjì chāoguò le wǒ.", "Thành tích của cậu ấy đã vượt qua tôi.", "Động từ"],
    ["散步", "sànbù", "đi dạo", "吃完饭我们去散步吧。", "Chī wán fàn wǒmen qù sànbù ba.", "Ăn xong chúng ta đi dạo nhé.", "Động từ"],
    ["指", "zhǐ", "chỉ, trỏ", "他指着前面的大楼。", "Tā zhǐ zhe qiánmiàn de dàlóu.", "Anh ấy chỉ vào tòa nhà phía trước.", "Động từ"],
    ["精神", "jīngshén", "tinh thần", "他的精神状态很好。", "Tā de jīngshén zhuàngtài hěn hǎo.", "Trạng thái tinh thần của anh ấy rất tốt.", "Danh từ"],
    ["教授", "jiàoshòu", "giáo sư", "王教授是我的老师。", "Wáng jiàoshòu shì wǒ de lǎoshī.", "Giáo sư Vương là thầy của tôi.", "Danh từ"],
    ["数字", "shùzì", "con số", "请写下这些数字。", "Qǐng xiě xià zhèxiē shùzì.", "Xin hãy viết xuống những con số này.", "Danh từ"],
    ["说明", "shuōmíng", "giải thích, thuyết minh", "请说明一下你的理由。", "Qǐng shuōmíng yíxià nǐ de lǐyóu.", "Xin hãy giải thích một chút lý do của bạn.", "Động từ/Danh từ"],
    ["要是", "yàoshì", "nếu như", "要是明天下雨，我们就不去了。", "Yàoshì míngtiān xiàyǔ, wǒmen jiù bú qù le.", "Nếu như ngày mai mưa, chúng ta sẽ không đi nữa.", "Liên từ"],
    ["既", "jì", "đã, vừa", "这件衣服既便宜又好看。", "Zhè jiàn yīfu jì piányi yòu hǎokàn.", "Bộ quần áo này vừa rẻ lại vừa đẹp.", "Liên từ"],
    ["减肥", "jiǎnféi", "giảm béo", "她正在努力减肥。", "Tā zhèngzài nǔlì jiǎnféi.", "Cô ấy đang nỗ lực giảm béo.", "Động từ"],
    ["辛苦", "xīnkǔ", "vất vả", "大家工作都挺辛苦的。", "Dàjiā gōngzuò dōu tǐng xīnkǔ de.", "Mọi người làm việc đều khá vất vả.", "Tính từ"],
    ["肚子", "dùzi", "bụng", "我肚子疼。", "Wǒ dùzi téng.", "Tôi đau bụng.", "Danh từ"],
    ["感情", "gǎnqíng", "tình cảm", "他们俩感情很好。", "Tāmen liǎ gǎnqíng hěn hǎo.", "Tình cảm của hai người họ rất tốt.", "Danh từ"],
    ["烦恼", "fánnǎo", "phiền não", "别为这件事烦恼了。", "Bié wèi zhè jiàn shì fánnǎo le.", "Đừng phiền não vì chuyện này nữa.", "Tính từ/Danh từ"],
    ["掉", "diào", "rơi, rớt", "我的钥匙掉在地上。", "Wǒ de yàoshi diào zài dìshàng.", "Chìa khóa của tôi rớt trên mặt đất.", "Động từ"]
],
  "hsk8": [
    ["巧克力", "qiǎokèlì", "sô-cô-la", "她送给我一盒巧克力。", "Tā sòng gěi wǒ yì hé qiǎokèlì.", "Cô ấy tặng tôi một hộp sô-cô-la.", "Danh từ"],
    ["亲戚", "qīnqi", "họ hàng", "春节时我们会去走亲戚。", "Chūnjié shí wǒmen huì qù zǒu qīnqi.", "Lúc Tết chúng tôi sẽ đi thăm họ hàng.", "Danh từ"],
    ["伤心", "shāngxīn", "đau lòng, buồn bã", "听到这个消息，我很伤心。", "Tīngdào zhège xiāoxi, wǒ hěn shāngxīn.", "Nghe được tin này, tôi rất buồn.", "Tính từ"],
    ["使", "shǐ", "khiến cho, làm cho", "这件事使他非常生气。", "Zhè jiàn shì shǐ tā fēicháng shēngqì.", "Chuyện này khiến anh ấy vô cùng tức giận.", "Động từ"],
    ["心疼", "xīnténg", "thương, xót xa", "看到她生病，我很心疼。", "Kàndào tā shēngbìng, wǒ hěn xīnténg.", "Thấy cô ấy ốm, tôi rất xót xa.", "Động từ"],
    ["心情", "xīnqíng", "tâm trạng", "我今天心情很好。", "Wǒ jīntiān xīnqíng hěn hǎo.", "Tâm trạng tôi hôm nay rất tốt.", "Danh từ"],
    ["愉快", "yúkuài", "vui vẻ", "祝你周末愉快！", "Zhù nǐ zhōumò yúkuài!", "Chúc bạn cuối tuần vui vẻ!", "Tính từ"],
    ["景色", "jǐngsè", "phong cảnh, cảnh sắc", "这里的景色真美。", "Zhèlǐ de jǐngsè zhēn měi.", "Phong cảnh ở đây thật đẹp.", "Danh từ"],
    ["放松", "fàngsōng", "thư giãn, thả lỏng", "听音乐可以让人放松。", "Tīng yīnyuè kěyǐ ràng rén fàngsōng.", "Nghe nhạc có thể giúp người ta thư giãn.", "Động từ"],
    ["拍", "pāi", "chụp (ảnh)", "我们一起拍张照吧。", "Wǒmen yìqǐ pāi zhāng zhào ba.", "Chúng ta cùng chụp một tấm ảnh đi.", "Động từ"],
    ["压力", "yālì", "áp lực", "现在年轻人的工作压力很大。", "Xiànzài niánqīng rén de gōngzuò yālì hěn dà.", "Áp lực công việc của người trẻ hiện nay rất lớn.", "Danh từ"],
    ["回忆", "huíyì", "hồi ức, nhớ lại", "这首歌勾起了我的回忆。", "Zhè shǒu gē gōuqǐ le wǒ de huíyì.", "Bài hát này đã gợi lại hồi ức của tôi.", "Danh từ/Động từ"],
    ["发生", "fāshēng", "xảy ra", "这里发生了什么事？", "Zhèlǐ fāshēng le shénme shì?", "Ở đây đã xảy ra chuyện gì?", "Động từ"],
    ["成为", "chéngwéi", "trở thành", "他想成为一名医生。", "Tā xiǎng chéngwéi yì míng yīshēng.", "Cậu ấy muốn trở thành một bác sĩ.", "Động từ"],
    ["只要", "zhǐyào", "chỉ cần", "只要努力，就能成功。", "Zhǐyào nǔlì, jiù néng chénggōng.", "Chỉ cần nỗ lực thì sẽ thành công.", "Liên từ"],
    ["师傅", "shīfu", "sư phụ, bác tài, thợ", "师傅，请去火车站。", "Shīfu, qǐng qù huǒchēzhàn.", "Bác tài, xin đến ga tàu hỏa.", "Danh từ"],
    ["大使馆", "dàshǐguǎn", "đại sứ quán", "我要去大使馆办签证。", "Wǒ yào qù dàshǐguǎn bàn qiānzhèng.", "Tôi phải đến đại sứ quán làm visa.", "Danh từ"],
    ["堵车", "dǔchē", "tắc đường", "前面堵车了，我们换条路吧。", "Qiánmiàn dǔchē le, wǒmen huàn tiáo lù ba.", "Phía trước tắc đường rồi, chúng ta đổi đường khác đi.", "Động từ"],
    ["距离", "jùlí", "khoảng cách", "我家距离学校很近。", "Wǒ jiā jùlí xuéxiào hěn jìn.", "Nhà tôi cách trường rất gần.", "Danh từ"],
    ["耐心", "nàixīn", "kiên nhẫn", "教孩子需要很大的耐心。", "Jiāo háizi xūyào hěn dà de nàixīn.", "Dạy trẻ em cần sự kiên nhẫn rất lớn.", "Danh từ/Tính từ"],
    ["首都", "shǒudū", "thủ đô", "河内是越南的首都。", "Hénèi shì Yuènán de shǒudū.", "Hà Nội là thủ đô của Việt Nam.", "Danh từ"],
    ["保持", "bǎochí", "giữ, duy trì", "我们要保持联系。", "Wǒmen yào bǎochí liánxì.", "Chúng ta phải giữ liên lạc.", "Động từ"],
    ["可不是", "kěbúshì", "đúng vậy, chính xác", "可不是嘛，今天真冷！", "Kěbúshì ma, jīntiān zhēn lěng!", "Đúng vậy mà, hôm nay lạnh thật!", "Cụm từ/Phó từ"],
    ["生命", "shēngmìng", "sinh mệnh, sự sống", "生命是非常宝贵的。", "Shēngmìng shì fēicháng bǎoguì de.", "Sinh mệnh là vô cùng quý giá.", "Danh từ"],
    ["缺少", "quēshǎo", "thiếu sót, thiếu", "我们缺少一些经验。", "Wǒmen quēshǎo yìxiē jīngyàn.", "Chúng ta thiếu một chút kinh nghiệm.", "Động từ"],
    ["到处", "dàochù", "khắp nơi", "公园里到处都是人。", "Gōngyuán lǐ dàochù dōu shì rén.", "Trong công viên đâu đâu cũng là người.", "Phó từ"],
    ["态度", "tàidu", "thái độ", "他的服务态度很好。", "Tā de fúwù tàidu hěn hǎo.", "Thái độ phục vụ của anh ấy rất tốt.", "Danh từ"],
    ["因此", "yīncǐ", "do đó, vì vậy", "他生病了，因此没来上课。", "Tā shēngbìng le, yīncǐ méi lái shàngkè.", "Anh ấy ốm rồi, do đó không đến lớp.", "Liên từ"],
    ["炒鱿鱼", "chǎoyóuyú", "sa thải, đuổi việc", "他上个月被老板炒鱿鱼了。", "Tā shàng gè yuè bèi lǎobǎn chǎoyóuyú le.", "Tháng trước anh ấy bị ông chủ sa thải rồi.", "Động từ"],
    ["行为", "xíngwéi", "hành vi", "我们要对自己的行为负责。", "Wǒmen yào duì zìjǐ de xíngwéi fùzé.", "Chúng ta phải chịu trách nhiệm cho hành vi của mình.", "Danh từ"],
    ["科学", "kēxué", "khoa học", "他对科学很感兴趣。", "Tā duì kēxué hěn gǎn xìngqù.", "Anh ấy rất có hứng thú với khoa học.", "Danh từ/Tính từ"],
    ["证明", "zhèngmíng", "chứng minh", "事实证明他是对的。", "Shìshí zhèngmíng tā shì duì de.", "Thực tế chứng minh anh ấy là đúng.", "Động từ/Danh từ"],
    ["往往", "wǎngwǎng", "thường thường, hay", "周末我往往在家里看书。", "Zhōumò wǒ wǎngwǎng zài jiālǐ kàn shū.", "Cuối tuần tôi thường ở nhà đọc sách.", "Phó từ"],
    ["阳光", "yángguāng", "ánh nắng / vui vẻ", "今天的阳光很明媚。", "Jīntiān de yángguāng hěn míngmèi.", "Ánh nắng hôm nay rất tươi sáng.", "Danh từ/Tính từ"],
    ["积极", "jījí", "tích cực", "我们要积极面对困难。", "Wǒmen yào jījí miànduì kùnnan.", "Chúng ta phải tích cực đối mặt khó khăn.", "Tính từ"],
    ["特点", "tèdiǎn", "đặc điểm", "这种产品的特点是什么？", "Zhè zhǒng chǎnpǐn de tèdiǎn shì shénme?", "Đặc điểm của loại sản phẩm này là gì?", "Danh từ"],
    ["工业区", "gōngyèqū", "khu công nghiệp", "他在附近的工业区上班。", "Tā zài fùjìn de gōngyèqū shàngbān.", "Anh ấy làm việc ở khu công nghiệp gần đây.", "Danh từ"]
],
  "hsk9": [
    ["饼干", "bǐnggān", "bánh quy", "这盒饼干很好吃。", "Zhè hé bǐnggān hěn hǎochī.", "Hộp bánh quy này rất ngon.", "Danh từ"],
    ["难道", "nándào", "lẽ nào, chẳng lẽ", "你难道不知道这件事吗？", "Nǐ nándào bù zhīdào zhè jiàn shì ma?", "Lẽ nào bạn không biết chuyện này?", "Phó từ"],
    ["得", "děi", "phải", "时间不早了，我得走了。", "Shíjiān bù zǎo le, wǒ děi zǒu le.", "Trời không còn sớm nữa, tôi phải đi rồi.", "Động từ năng nguyện"],
    ["坚持", "jiānchí", "kiên trì", "只要坚持，就一定会成功。", "Zhǐyào jiānchí, jiù yídìng huì chénggōng.", "Chỉ cần kiên trì, thì nhất định sẽ thành công.", "Động từ"],
    ["放弃", "fàngqì", "từ bỏ", "不要轻易放弃你的梦想。", "Búyào qīngyì fàngqì nǐ de mèngxiǎng.", "Đừng dễ dàng từ bỏ ước mơ của bạn.", "Động từ"],
    ["主意", "zhǔyi", "ý kiến, chủ ý", "这个主意不错。", "Zhège zhǔyi búcuò.", "Chủ ý này không tồi.", "Danh từ"],
    ["网球", "wǎngqiú", "quần vợt, tennis", "他喜欢打网球。", "Tā xǐhuan dǎ wǎngqiú.", "Cậu ấy thích chơi tennis.", "Danh từ"],
    ["国际", "guójì", "quốc tế", "这是一家国际公司。", "Zhè shì yì jiā guójì gōngsī.", "Đây là một công ty quốc tế.", "Tính từ"],
    ["轻松", "qīngsōng", "nhẹ nhõm, thư giãn", "考完试，我觉得很轻松。", "Kǎo wán shì, wǒ juéde hěn qīngsōng.", "Thi xong, tôi cảm thấy rất nhẹ nhõm.", "Tính từ"],
    ["赢", "yíng", "thắng", "这场比赛我们赢了。", "Zhè chǎng bǐsài wǒmen yíng le.", "Trận đấu này chúng tôi thắng rồi.", "Động từ"],
    ["随便", "suíbiàn", "tùy tiện, tùy ý", "请随便坐。", "Qǐng suíbiàn zuò.", "Mời ngồi tùy ý.", "Tính từ/Phó từ"],
    ["汗", "hàn", "mồ hôi", "他出了很多汗。", "Tā chū le hěn duō hàn.", "Anh ấy đổ rất nhiều mồ hôi.", "Danh từ"],
    ["通过", "tōngguò", "thông qua", "他通过了汉语考试。", "Tā tōngguò le Hànyǔ kǎoshì.", "Anh ấy đã thông qua kỳ thi tiếng Hán.", "Động từ/Giới từ"],
    ["篇", "piān", "bài (lượng từ của văn bản)", "这是一篇好文章。", "Zhè shì yì piān hǎo wénzhāng.", "Đây là một bài văn hay.", "Lượng từ"],
    ["作家", "zuòjiā", "nhà văn", "他是一位著名的作家。", "Tā shì yí wèi zhùmíng de zuòjiā.", "Ông ấy là một nhà văn nổi tiếng.", "Danh từ"],
    ["当时", "dāngshí", "lúc đó", "当时我不在家。", "Dāngshí wǒ bú zài jiā.", "Lúc đó tôi không có ở nhà.", "Danh từ"],
    ["可是", "kěshì", "nhưng", "我想去，可是没时间。", "Wǒ xiǎng qù, kěshì méi shíjiān.", "Tôi muốn đi, nhưng không có thời gian.", "Liên từ"],
    ["正确", "zhèngquè", "chính xác", "你的答案是正确的。", "Nǐ de dá'àn shì zhèngquè de.", "Đáp án của bạn là chính xác.", "Tính từ"],
    ["理想", "lǐxiǎng", "lý tưởng", "我的理想是当一名老师。", "Wǒ de lǐxiǎng shì dāng yì míng lǎoshī.", "Lý tưởng của tôi là làm một giáo viên.", "Danh từ/Tính từ"],
    ["勇敢", "yǒnggǎn", "dũng cảm", "他是一个勇敢的人。", "Tā shì yí ge yǒnggǎn de rén.", "Anh ấy là một người dũng cảm.", "Tính từ"],
    ["结果", "jiéguǒ", "kết quả", "我们还在等考试结果。", "Wǒmen hái zài děng kǎoshì jiéguǒ.", "Chúng tôi vẫn đang đợi kết quả thi.", "Danh từ"],
    ["失败", "shībài", "thất bại", "失败是成功之母。", "Shībài shì chénggōng zhī mǔ.", "Thất bại là mẹ thành công.", "Động từ/Danh từ"],
    ["过程", "guòchéng", "quá trình", "学习的过程很辛苦。", "Xuéxí de guòchéng hěn xīnkǔ.", "Quá trình học tập rất vất vả.", "Danh từ"],
    ["至少", "zhìshǎo", "ít nhất", "他至少三十岁了。", "Tā zhìshǎo sānshí suì le.", "Anh ấy ít nhất cũng 30 tuổi rồi.", "Phó từ"],
    ["总结", "zǒngjié", "tổng kết", "请你总结一下今天的内容。", "Qǐng nǐ zǒngjié yíxià jīntiān de nèiróng.", "Xin hãy tổng kết lại nội dung ngày hôm nay.", "Động từ"],
    ["取", "qǔ", "lấy", "我去银行取钱。", "Wǒ qù yínháng qǔ qián.", "Tôi đến ngân hàng lấy tiền.", "Động từ"],
    ["经历", "jīnglì", "trải nghiệm, trải qua", "这是一段难忘的经历。", "Zhè shì yí duàn nánwàng de jīnglì.", "Đây là một trải nghiệm khó quên.", "Danh từ/Động từ"],
    ["许多", "xǔduō", "rất nhiều", "这里有许多漂亮的花。", "Zhèlǐ yǒu xǔduō piàoliang de huā.", "Ở đây có rất nhiều hoa đẹp.", "Tính từ"],
    ["区别", "qūbié", "phân biệt, sự khác biệt", "你知道这两个词的区别吗？", "Nǐ zhīdào zhè liǎng ge cí de qūbié ma?", "Bạn có biết sự khác biệt của hai từ này không?", "Danh từ/Động từ"],
    ["暂时", "zànshí", "tạm thời", "我暂时没有其他问题。", "Wǒ zànshí méiyǒu qítā wèntí.", "Tôi tạm thời không có câu hỏi nào khác.", "Phó từ"],
    ["面对", "miànduì", "đối mặt", "我们要勇敢面对困难。", "Wǒmen yào yǒnggǎn miànduì kùnnan.", "Chúng ta phải dũng cảm đối mặt với khó khăn.", "Động từ"]
  ],
  "hsk10": [
    ["礼拜天", "lǐbàitiān", "Chủ nhật", "我们礼拜天去爬山。", "Wǒmen lǐbàitiān qù páshān.", "Chủ nhật chúng tôi đi leo núi.", "Danh từ"],
    ["空儿", "kòngr", "thời gian rảnh", "你明天有空儿吗？", "Nǐ míngtiān yǒu kòngr ma?", "Ngày mai bạn có rảnh không?", "Danh từ"],
    ["母亲", "mǔqīn", "người mẹ", "我的母亲是一名医生。", "Wǒ de mǔqīn shì yì míng yīshēng.", "Mẹ của tôi là một bác sĩ.", "Danh từ"],
    ["不过", "búguò", "nhưng, có điều", "这件衣服好看，不过太贵了。", "Zhè jiàn yīfu hǎokàn, búguò tài guì le.", "Bộ quần áo này đẹp, có điều quá đắt.", "Liên từ/Phó từ"],
    ["永远", "yǒngyuǎn", "mãi mãi", "我会永远记住你的好。", "Wǒ huì yǒngyuǎn jìzhu nǐ de hǎo.", "Tôi sẽ mãi mãi nhớ sự tốt bụng của bạn.", "Phó từ"],
    ["方向", "fāngxiàng", "phương hướng", "你走错方向了。", "Nǐ zǒu cuò fāngxiàng le.", "Bạn đi nhầm hướng rồi.", "Danh từ"],
    ["优秀", "yōuxiù", "xuất sắc", "他是一个非常优秀的学生。", "Tā shì yí ge fēicháng yōuxiù de xuéshēng.", "Cậu ấy là một học sinh vô cùng xuất sắc.", "Tính từ"],
    ["硕士", "shuòshì", "thạc sĩ", "他在读硕士研究生。", "Tā zài dú shuòshì yánjiūshēng.", "Anh ấy đang học nghiên cứu sinh thạc sĩ.", "Danh từ"],
    ["翻译", "fānyì", "dịch, phiên dịch", "请把这句话翻译成汉语。", "Qǐng bǎ zhè jù huà fānyì chéng Hànyǔ.", "Xin hãy dịch câu này sang tiếng Hán.", "Động từ/Danh từ"],
    ["确实", "quèshí", "thực sự, quả thật", "他确实是个好人。", "Tā quèshí shì ge hǎorén.", "Anh ấy quả thật là một người tốt.", "Phó từ"],
    ["兴奋", "xīngfèn", "hưng phấn, hào hứng", "听到这个消息，他很兴奋。", "Tīngdào zhège xiāoxi, tā hěn xīngfèn.", "Nghe được tin này, anh ấy rất hào hứng.", "Tính từ"],
    ["拉", "lā", "kéo", "他拉着我的手。", "Tā lā zhe wǒ de shǒu.", "Anh ấy kéo tay tôi.", "Động từ"],
    ["建议", "jiànyì", "kiến nghị, đề nghị", "我建议你多休息。", "Wǒ jiànyì nǐ duō xiūxi.", "Tôi đề nghị bạn nghỉ ngơi nhiều hơn.", "Động từ/Danh từ"],
    ["职业", "zhíyè", "nghề nghiệp", "你的职业是什么？", "Nǐ de zhíyè shì shénme?", "Nghề nghiệp của bạn là gì?", "Danh từ"],
    ["关键", "guānjiàn", "mấu chốt", "解决问题的关键是沟通。", "Jiějué wèntí de guānjiàn shì gōutōng.", "Mấu chốt của việc giải quyết vấn đề là giao tiếp.", "Danh từ/Tính từ"],
    ["将来", "jiānglái", "tương lai", "你将来想做什么？", "Nǐ jiānglái xiǎng zuò shénme?", "Tương lai bạn muốn làm gì?", "Danh từ"],
    ["发展", "fāzhǎn", "phát triển", "这座城市发展得很快。", "Zhè zuò chéngshì fāzhǎn de hěn kuài.", "Thành phố này phát triển rất nhanh.", "Động từ/Danh từ"],
    ["躺", "tǎng", "nằm", "他正躺在床上看书。", "Tā zhèng tǎng zài chuáng shàng kàn shū.", "Anh ấy đang nằm trên giường đọc sách.", "Động từ"],
    ["困", "kùn", "buồn ngủ", "我有点儿困了。", "Wǒ yǒudiǎnr kùn le.", "Tôi hơi buồn ngủ rồi.", "Tính từ"],
    ["经济", "jīngjì", "kinh tế", "这个国家的经济发展很好。", "Zhège guójiā de jīngjì fāzhǎn hěn hǎo.", "Nền kinh tế của quốc gia này phát triển rất tốt.", "Danh từ"],
    ["条件", "tiáojiàn", "điều kiện", "我们公司的条件很好。", "Wǒmen gōngsī de tiáojiàn hěn hǎo.", "Điều kiện của công ty chúng tôi rất tốt.", "Danh từ"],
    ["富", "fù", "giàu có", "他是一个很富的人。", "Tā shì yí ge hěn fù de rén.", "Ông ấy là một người rất giàu có.", "Tính từ"],
    ["穷", "qióng", "nghèo", "即使很穷，他也很开心。", "Jíshǐ hěn qióng, tā yě hěn kāixīn.", "Cho dù rất nghèo, anh ấy cũng rất vui vẻ.", "Tính từ"],
    ["等", "děng", "vân vân, đợi", "我喜欢苹果、香蕉等水果。", "Wǒ xǐhuan píngguǒ, xiāngjiāo děng shuǐguǒ.", "Tôi thích các loại trái cây như táo, chuối, v.v.", "Trợ từ/Động từ"],
    ["由于", "yóuyú", "bởi vì, do", "由于天气原因，航班取消了。", "Yóuyú tiānqì yuányīn, hángbān qǔxiāo le.", "Do nguyên nhân thời tiết, chuyến bay đã bị hủy.", "Liên từ/Giới từ"],
    ["比如", "bǐrú", "ví dụ như", "我喜欢运动，比如游泳、跑步。", "Wǒ xǐhuan yùndòng, bǐrú yóuyǒng, pǎobù.", "Tôi thích vận động, ví dụ như bơi lội, chạy bộ.", "Động từ"],
    ["橡皮", "xiàngpí", "cục tẩy", "你能借我一块橡皮吗？", "Nǐ néng jiè wǒ yí kuài xiàngpí ma?", "Bạn có thể cho tôi mượn một cục tẩy không?", "Danh từ"],
    ["糖", "táng", "đường, kẹo", "我不喜欢吃太多的糖。", "Wǒ bù xǐhuan chī tài duō de táng.", "Tôi không thích ăn quá nhiều đường.", "Danh từ"],
    ["低", "dī", "thấp", "这里的温度很低。", "Zhèlǐ de wēndù hěn dī.", "Nhiệt độ ở đây rất thấp.", "Tính từ"],
    ["答案", "dá'àn", "đáp án", "你知道这个问题的答案吗？", "Nǐ zhīdào zhège wèntí de dá'àn ma?", "Bạn có biết đáp án của câu hỏi này không?", "Danh từ"]
  ],
 "hsk11": [
   ["流利", "liúlì", "lưu loát, trôi chảy", "你来中国才一年，汉语就说得这么流利。", "Nǐ lái Zhōngguó cái yì nián, Hànyǔ jiù shuō de zhème liúlì.", "Bạn đến Trung Quốc mới một năm mà tiếng Hán đã nói lưu loát như vậy.", "Tính từ"],
    ["厉害", "lìhai", "lợi hại, giỏi, nghiêm trọng", "他玩游戏非常厉害。", "Tā wán yóuxì fēicháng lìhai.", "Anh ấy chơi game rất giỏi/lợi hại.", "Tính từ"],
    ["准确", "zhǔnquè", "chính xác, chuẩn, đúng", "我的语法不太好，很多句子说得不太准确。", "Wǒ de yǔfǎ bú tài hǎo, hěn duō jùzi shuō de bú tài zhǔnquè.", "Ngữ pháp của tôi không tốt lắm, nhiều câu nói không được chuẩn xác.", "Tính từ"],
    ["迎接", "yíngjiē", "chào đón", "我们去机场迎接客人。", "Wǒmen qù jīchǎng yíngjiē kèrén.", "Chúng tôi ra sân bay chào đón khách.", "Động từ"],
    ["语法", "yǔfǎ", "ngữ pháp", "汉语语法其实不太难。", "Hànyǔ yǔfǎ qíshí bú tài nán.", "Ngữ pháp tiếng Trung thực ra không quá khó.", "Danh từ"],
    ["词语", "cíyǔ", "từ ngữ, từ vựng", "多看中文报纸能学到很多新词语。", "Duō kàn Zhōngwén bàozhǐ néng xuédào hěn duō xīn cíyǔ.", "Đọc nhiều báo tiếng Trung có thể học được rất nhiều từ vựng mới.", "Danh từ"],
    ["连", "lián", "ngay cả (... cũng/đều)", "这个问题太难了，连老师也不会。", "Zhège wèntí tài nán le, lián lǎoshī yě bú huì.", "Vấn đề này khó quá, ngay cả giáo viên cũng không biết.", "Giới từ"],
    ["阅读", "yuèdú", "đọc, đọc hiểu", "这次阅读考试的题太多了。", "Zhè cì yuèdú kǎoshì de tí tài duō le.", "Đề thi đọc hiểu lần này nhiều quá.", "Động từ/Danh từ"],
    ["听力", "tīnglì", "nghe hiểu", "我要多练习听力。", "Wǒ yào duō liànxí tīnglì.", "Tôi phải luyện tập nghe hiểu nhiều hơn.", "Danh từ"],
    ["书写", "shūxiě", "viết", "他的书写很整齐。", "Tā de shūxiě hěn zhěngqí.", "Chữ viết của anh ấy rất ngay ngắn.", "Động từ/Danh từ"],
    ["口语", "kǒuyǔ", "khẩu ngữ", "我想提高我的汉语口语。", "Wǒ xiǎng tígāo wǒ de Hànyǔ kǒuyǔ.", "Tôi muốn nâng cao khẩu ngữ tiếng Trung của mình.", "Danh từ"],
    ["题", "tí", "đề, câu", "这道题我不知道怎么做。", "Zhè dào tí wǒ bù zhīdào zěnme zuò.", "Câu hỏi này tôi không biết làm thế nào.", "Danh từ"],
    ["来得及", "láidejí", "kịp, còn kịp", "两个小时的时间应该来得及吧？", "Liǎng ge xiǎoshí de shíjiān yīnggāi láidejí ba?", "Thời gian hai tiếng đồng hồ chắc là kịp nhỉ?", "Động từ"],
    ["来不及", "láibují", "không kịp", "快点儿走，要来不及了。", "Kuài diǎnr zǒu, yào láibují le.", "Đi nhanh lên, sắp không kịp rồi.", "Động từ"],
    ["忙着", "mángzhe", "bận làm gì", "他正忙着准备明天的考试。", "Tā zhèng mángzhe zhǔnběi míngtiān de kǎoshì.", "Anh ấy đang bận chuẩn bị cho kỳ thi ngày mai.", "Động từ"],
    ["复杂", "fùzá", "phức tạp, rắc rối", "我先做了比较复杂的题。", "Wǒ xiān zuò le bǐjiào fùzá de tí.", "Tôi đã làm những câu tương đối phức tạp trước.", "Tính từ"],
    ["只好", "zhǐhǎo", "đành phải, buộc phải", "最后只好放弃了。", "Zuìhòu zhǐhǎo fàngqì le.", "Cuối cùng đành phải từ bỏ.", "Phó từ"],
    ["否则", "fǒuzé", "nếu không thì, bằng không", "考试要认真，否则会做错。", "Kǎoshì yào rènzhēn, fǒuzé huì zuò cuò.", "Thi cử phải nghiêm túc, nếu không thì sẽ làm sai.", "Liên từ"],
    ["填空", "tiánkòng", "điền vào chỗ trống", "有几个填空题不会做。", "Yǒu jǐ ge tiánkòng tí bú huì zuò.", "Có mấy câu điền vào chỗ trống không biết làm.", "Động từ"],
    ["猜", "cāi", "đoán", "结果一个都没猜对。", "Jiéguǒ yí ge dōu méi cāi duì.", "Kết quả là không đoán đúng một câu nào.", "Động từ"],
    ["随便", "suíbiàn", "thoải mái, tuỳ", "我就随便猜了一个答案。", "Wǒ jiù suíbiàn cāi le yí ge dá'àn.", "Tôi liền đoán bừa/tùy tiện một đáp án.", "Tính từ/Phó từ"],
    ["客厅", "kètīng", "phòng khách", "我家客厅很大。", "Wǒ jiā kètīng hěn dà.", "Phòng khách nhà tôi rất lớn.", "Danh từ"],
    ["无论", "wúlùn", "bất luận, bất kể", "无论多忙，他都坚持锻炼。", "Wúlùn duō máng, tā dōu jiānchí duànliàn.", "Dù bận thế nào, anh ấy đều kiên trì rèn luyện.", "Liên từ"],
    ["杂志", "zázhì", "tạp chí", "桌子上有一本杂志。", "Zhuōzi shàng yǒu yì běn zázhì.", "Trên bàn có một cuốn tạp chí.", "Danh từ"],
    ["著名", "zhùmíng", "nổi tiếng", "他是一位著名的作家。", "Tā shì yí wèi zhùmíng de zuòjiā.", "Ông ấy là một nhà văn nổi tiếng.", "Tính từ"],
    ["页", "yè", "trang", "这本书有三百页。", "Zhè běn shū yǒu sān bǎi yè.", "Cuốn sách này có 300 trang.", "Lượng từ"],
    ["增加", "zēngjiā", "tăng thêm", "阅读能增加我们的知识。", "Yuèdú néng zēngjiā wǒmen de zhīshi.", "Đọc sách có thể tăng thêm kiến thức cho chúng ta.", "Động từ"],
    ["文章", "wénzhāng", "bài văn, bài báo", "这篇文章写得很好。", "Zhè piān wénzhāng xiě de hěn hǎo.", "Bài văn này viết rất hay.", "Danh từ"],
    ["之", "zhī", "của (dùng nối từ bổ nghĩa và được bổ nghĩa)", "三分之一", "Sān fēn zhī yī", "Một phần ba", "Trợ từ"],
    ["内容", "nèiróng", "nội dung", "这篇文章的内容很丰富。", "Zhè piān wénzhāng de nèiróng hěn fēngfù.", "Nội dung của bài viết này rất phong phú.", "Danh từ"],
    ["然而", "rán'ér", "nhưng, song", "他很聪明，然而不太努力。", "Tā hěn cōngming, rán'ér bú tài nǔlì.", "Anh ấy rất thông minh, nhưng không nỗ lực lắm.", "Liên từ"],
    ["看法", "kànfǎ", "quan điểm, cách nhìn", "每个人都有自己的看法。", "Měi ge rén dōu yǒu zìjǐ de kànfǎ.", "Mỗi người đều có quan điểm riêng của mình.", "Danh từ"],
    ["相同", "xiāngtóng", "giống nhau, như nhau", "我们的爱好相同。", "Wǒmen de àihào xiāngtóng.", "Sở thích của chúng tôi giống nhau.", "Tính từ"],
    ["顺序", "shùnxù", "trật tự, thứ tự", "请按顺序排队。", "Qǐng àn shùnxù páiduì.", "Xin hãy xếp hàng theo thứ tự.", "Danh từ"],
    ["表示", "biǎoshì", "biểu thị, có ý nghĩa", "点头表示同意。", "Diǎntóu biǎoshì tóngyì.", "Gật đầu biểu thị sự đồng ý.", "Động từ"],
    ["养成", "yǎngchéng", "hình thành, tạo (thói quen)", "从小要养成好习惯。", "Cóngxiǎo yào yǎngchéng hǎo xíguàn.", "Từ nhỏ phải hình thành thói quen tốt.", "Động từ"],
    ["同时", "tóngshí", "đồng thời, hơn nữa", "阅读的同时，还会有很多新发现。", "Yuèdú de tóngshí, hái huì yǒu hěn duō xīn fāxiàn.", "Đồng thời với việc đọc, còn có thể có nhiều phát hiện mới.", "Liên từ/Danh từ"],
    ["精彩", "jīngcǎi", "tuyệt vời, xuất sắc", "这场比赛非常精彩。", "Zhè chǎng bǐsài fēicháng jīngcǎi.", "Trận đấu này vô cùng đặc sắc.", "Tính từ"]
 ],
  "hsk12": [
    ["航班", "hángbān", "chuyến bay", "您的航班马上就要起飞了。", "Nín de hángbān mǎshàng jiù yào qǐfēi le.", "Chuyến bay của ngài sắp cất cánh rồi.", "Danh từ"],
    ["乘坐", "chéngzuò", "đi, ngồi (xe, tàu, máy bay)", "欢迎乘坐本次航班。", "Huānyíng chéngzuò běn cì hángbān.", "Chào mừng đi trên chuyến bay lần này.", "Động từ"],
    ["推迟", "tuīchí", "trì hoãn, lùi lại", "因为天气原因，会议推迟了。", "Yīnwèi tiānqì yuányīn, huìyì tuīchí le.", "Vì nguyên nhân thời tiết, cuộc họp đã bị lùi lại.", "Động từ"],
    ["降落", "jiàngluò", "hạ cánh", "飞机还有十分钟降落。", "Fēijī hái yǒu shí fēnzhōng jiàngluò.", "Máy bay còn 10 phút nữa hạ cánh.", "Động từ"],
    ["广播", "guǎngbō", "phát thanh", "听广播可以提高听力。", "Tīng guǎngbō kěyǐ tígāo tīnglì.", "Nghe phát thanh có thể nâng cao kỹ năng nghe.", "Danh từ/Động từ"],
    ["于是", "yúshì", "thế là, ngay sau đó", "太晚了，于是我就在酒店住下了。", "Tài wǎn le, yúshì wǒ jiù zài jiǔdiàn zhù xià le.", "Muộn quá rồi, thế là tôi ở lại khách sạn luôn.", "Liên từ"],
    ["无论", "wúlùn", "bất luận, dù cho", "无论多难，我都要坚持。", "Wúlùn duō nán, wǒ dōu yào jiānchí.", "Dù khó khăn thế nào, tôi cũng phải kiên trì.", "Liên từ"],
    ["随着", "suízhe", "cùng với", "随着时间的发展，城市变化很大。", "Suízhe shíjiān de fāzhǎn, chéngshì biànhuà hěn dà.", "Cùng với sự phát triển của thời gian, thành phố thay đổi rất nhiều.", "Giới từ"],
    ["凉快", "liángkuai", "mát mẻ", "秋天的天气很凉快。", "Qiūtiān de tiānqì hěn liángkuai.", "Thời tiết mùa thu rất mát mẻ.", "Tính từ"],
    ["暖和", "nuǎnhuo", "ấm áp", "春天到了，天气暖和了。", "Chūntiān dào le, tiānqì nuǎnhuo le.", "Mùa xuân đến rồi, thời tiết ấm áp rồi.", "Tính từ"],
    ["严格", "yángé", "nghiêm khắc", "老师对我们的要求很严格。", "Lǎoshī duì wǒmen de yāoqiú hěn yángé.", "Giáo viên yêu cầu đối với chúng tôi rất nghiêm khắc.", "Tính từ"],
    ["准确", "zhǔnquè", "chính xác", "你的发音非常准确。", "Nǐ de fāyīn fēicháng zhǔnquè.", "Phát âm của bạn vô cùng chính xác.", "Tính từ"],
    ["左右", "zuǒyòu", "khoảng, chừng", "他大概三十岁左右。", "Tā dàgài sānshí suì zuǒyòu.", "Anh ấy khoảng chừng 30 tuổi.", "Danh từ"],
    ["基础", "jīchǔ", "cơ sở, nền tảng", "学习汉语，基础很重要。", "Xuéxí Hànyǔ, jīchǔ hěn zhòngyào.", "Học tiếng Hán, nền tảng rất quan trọng.", "Danh từ"],
    ["语法", "yǔfǎ", "ngữ pháp", "汉语的语法不太难。", "Hànyǔ de yǔfǎ bú tài nán.", "Ngữ pháp tiếng Hán không quá khó.", "Danh từ"],
    ["词语", "cíyǔ", "từ ngữ", "请用这些词语造句。", "Qǐng yòng zhèxiē cíyǔ zàojù.", "Xin hãy dùng những từ ngữ này để đặt câu.", "Danh từ"],
    ["预习", "yùxí", "chuẩn bị bài", "上课前要好好预习。", "Shàngkè qián yào hǎohǎo yùxí.", "Trước khi lên lớp phải chuẩn bị bài thật tốt.", "Động từ"],
    ["阅读", "yuèdú", "đọc hiểu", "我的阅读能力还需要提高。", "Wǒ de yuèdú nénglì hái xūyào tígāo.", "Năng lực đọc hiểu của tôi còn cần nâng cao.", "Động từ/Danh từ"],
    ["复杂", "fùzá", "phức tạp", "这个问题越来越复杂了。", "Zhège wèntí yuè lái yuè fùzá le.", "Vấn đề này càng ngày càng phức tạp rồi.", "Tính từ"],
    ["讨论", "tǎolùn", "thảo luận", "我们正在讨论下个月的计划。", "Wǒmen zhèngzài tǎolùn xià ge yuè de jìhuà.", "Chúng tôi đang thảo luận kế hoạch của tháng sau.", "Động từ"],
    ["解释", "jiěshì", "giải thích", "请听我解释。", "Qǐng tīng wǒ jiěshì.", "Xin hãy nghe tôi giải thích.", "Động từ"],
    ["详细", "xiángxì", "chi tiết, tường tận", "请把这件事详细地说一遍。", "Qǐng bǎ zhè jiàn shì xiángxì de shuō yí biàn.", "Xin hãy kể lại chuyện này một cách chi tiết.", "Tính từ"],
    ["误会", "wùhuì", "hiểu lầm", "这完全是一个误会。", "Zhè wánquán shì yí ge wùhuì.", "Đây hoàn toàn là một sự hiểu lầm.", "Danh từ/Động từ"],
    ["杂志", "zázhì", "tạp chí", "我喜欢看时尚杂志。", "Wǒ xǐhuan kàn shíshàng zázhì.", "Tôi thích xem tạp chí thời trang.", "Danh từ"],
    ["支持", "zhīchí", "ủng hộ", "感谢大家的支持。", "Gǎnxiè dàjiā de zhīchí.", "Cảm ơn sự ủng hộ của mọi người.", "Động từ/Danh từ"]
  ],
  "hsk13": [
    ["到底", "dàodǐ", "rốt cuộc", "你到底去不去？", "Nǐ dàodǐ qù bú qù?", "Rốt cuộc bạn có đi hay không?", "Phó từ"],
    ["既然", "jìrán", "đã, nếu đã", "既然来了，就吃完饭再走吧。", "Jìrán lái le, jiù chī wán fàn zài zǒu ba.", "Nếu đã đến rồi, thì ăn cơm xong hẵng đi.", "Liên từ"],
    ["偶尔", "ǒu'ěr", "thỉnh thoảng", "我偶尔会去那家咖啡馆。", "Wǒ ǒu'ěr huì qù nà jiā kāfēiguǎn.", "Thỉnh thoảng tôi có đến quán cà phê đó.", "Phó từ"],
    ["也许", "yěxǔ", "có lẽ", "也许他是对的。", "Yěxǔ tā shì duì de.", "Có lẽ anh ấy đúng.", "Phó từ"],
    ["并且", "bìngqiě", "đồng thời, và", "他聪明并且很努力。", "Tā cōngming bìngqiě hěn nǔlì.", "Anh ấy thông minh và rất chăm chỉ.", "Liên từ"],
    ["力气", "lìqi", "sức lực", "我没有力气搬这个箱子。", "Wǒ méiyǒu lìqi bān zhège xiāngzi.", "Tôi không có sức để bê cái thùng này.", "Danh từ"],
    ["任务", "rènwu", "nhiệm vụ", "今天的任务比较重。", "Jīntiān de rènwu bǐjiào zhòng.", "Nhiệm vụ hôm nay tương đối nặng.", "Danh từ"],
    ["意见", "yìjiàn", "ý kiến", "大家有什么意见？", "Dàjiā yǒu shénme yìjiàn?", "Mọi người có ý kiến gì không?", "Danh từ"],
    ["达到", "dádào", "đạt đến, đạt được", "我们的目标已经达到了。", "Wǒmen de mùbiāo yǐjīng dádào le.", "Mục tiêu của chúng ta đã đạt được rồi.", "Động từ"],
    ["报道", "bàodào", "đưa tin, bài báo", "新闻报道了这件事。", "Xīnwén bàodào le zhè jiàn shì.", "Tin tức đã đưa tin về chuyện này.", "Động từ/Danh từ"],
    ["报名", "bàomíng", "đăng ký", "我想报名参加比赛。", "Wǒ xiǎng bàomíng cānjiā bǐsài.", "Tôi muốn đăng ký tham gia thi đấu.", "Động từ"],
    ["抱", "bào", "ôm", "母亲抱着孩子。", "Mǔqīn bào zhe háizi.", "Người mẹ đang ôm đứa con.", "Động từ"],
    ["抱歉", "bàoqiàn", "xin lỗi, áy náy", "很抱歉，我迟到了。", "Hěn bàoqiàn, wǒ chídào le.", "Rất xin lỗi, tôi đến muộn rồi.", "Tính từ"],
    ["笨", "bèn", "ngốc, ngốc nghếch", "我真是太笨了。", "Wǒ zhēn shì tài bèn le.", "Tôi đúng là ngốc quá đi.", "Tính từ"],
    ["遍", "biàn", "lần, lượt (từ đầu đến cuối)", "请再说一遍。", "Qǐng zài shuō yí biàn.", "Xin hãy nói lại một lần nữa.", "Lượng từ"],
    ["表格", "biǎogé", "bảng biểu", "请填写这张表格。", "Qǐng tiánxiě zhè zhāng biǎogé.", "Xin hãy điền vào bảng biểu này.", "Danh từ"],
    ["表示", "biǎoshì", "biểu thị, bày tỏ", "他对我表示感谢。", "Tā duì wǒ biǎoshì gǎnxiè.", "Anh ấy bày tỏ sự cảm ơn đối với tôi.", "Động từ"],
    ["表扬", "biǎoyáng", "biểu dương, khen ngợi", "老师表扬了他。", "Lǎoshī biǎoyáng le tā.", "Giáo viên đã khen ngợi anh ấy.", "Động từ"],
    ["博士", "bóshì", "tiến sĩ", "他在读博士。", "Tā zài dú bóshì.", "Anh ấy đang học tiến sĩ.", "Danh từ"],
    ["部分", "bùfen", "phần, bộ phận", "这只是其中的一部分。", "Zhè zhǐshì qízhōng de yí bùfen.", "Đây chỉ là một phần trong đó.", "Danh từ"],
    ["擦", "cā", "lau, chùi", "请把桌子擦干净。", "Qǐng bǎ zhuōzi cā gānjìng.", "Xin hãy lau sạch bàn.", "Động từ"],
    ["猜", "cāi", "đoán", "你猜我刚才看到了谁？", "Nǐ cāi wǒ gāngcái kàndào le shéi?", "Bạn đoán xem vừa nãy tôi nhìn thấy ai?", "Động từ"],
    ["参观", "cānguān", "tham quan", "周末我们要去参观博物馆。", "Zhōumò wǒmen yào qù cānguān bówùguǎn.", "Cuối tuần chúng tôi sẽ đi tham quan viện bảo tàng.", "Động từ"],
    ["参加", "cānjiā", "tham gia", "你想参加什么活动？", "Nǐ xiǎng cānjiā shénme huódòng?", "Bạn muốn tham gia hoạt động gì?", "Động từ"],
    ["材料", "cáiliào", "tài liệu", "请准备好开会的材料。", "Qǐng zhǔnbèi hǎo kāihuì de cáiliào.", "Xin hãy chuẩn bị tốt tài liệu họp.", "Danh từ"]
  ],
"hsk14": [
    ["牙膏", "yágāo", "kem đánh răng", "早上刷牙的时候，牙膏用完了。", "Zǎoshang shuāyá de shíhou, yágāo yòng wán le.", "Buổi sáng lúc đánh răng, kem đánh răng đã dùng hết rồi.", "Danh từ"],
    ["牙刷", "yáshuā", "bàn chải", "医生建议三个月换一把新牙刷。", "Yīshēng jiànyì sān ge yuè huàn yì bǎ xīn yáshuā.", "Bác sĩ khuyên 3 tháng nên thay một chiếc bàn chải mới.", "Danh từ"],
    ["仓库", "cāngkù", "kho, nhà kho", "工人们正在仓库里搬运货物。", "Gōngrénmen zhèngzài cāngkù lǐ bānyùn huòwù.", "Các công nhân đang vận chuyển hàng hóa trong kho.", "Danh từ"],
    ["省", "shěng", "tiết kiệm", "乘坐地铁不仅快，还能省不少钱。", "Chéngzuò dìtiě bùjǐn kuài, hái néng shěng bù shǎo qián.", "Đi tàu điện ngầm không chỉ nhanh mà còn tiết kiệm được khá nhiều tiền.", "Động từ"],
    ["成本", "chéngběn", "chi phí", "我们要想办法降低生产成本。", "Wǒmen yào xiǎng bànfǎ jiàngdī shēngchǎn chéngběn.", "Chúng ta phải tìm cách giảm chi phí sản xuất.", "Danh từ"],
    ["污染", "wūrǎn", "ô nhiễm", "保护环境，减少塑料对海洋的污染。", "Bǎohù huánjìng, jiǎnshǎo sùliào duì hǎiyáng de wūrǎn.", "Bảo vệ môi trường, giảm thiểu ô nhiễm nhựa đối với đại dương.", "Động từ/Danh từ"],
    ["垃圾", "lājī", "rác", "请把垃圾扔进垃圾桶里。", "Qǐng bǎ lājī rēng jìn lājītǒng lǐ.", "Xin hãy vứt rác vào trong thùng rác.", "Danh từ"],
    ["脏", "zāng", "bẩn", "你的衣服脏了，快去换一件吧。", "Nǐ de yīfu zāng le, kuài qù huàn yí jiàn ba.", "Quần áo của bạn bẩn rồi, mau đi thay một bộ khác đi.", "Tính từ"],
    ["弄", "nòng", "làm, làm cho", "我不小心把裤子弄脏了。", "Wǒ bù xiǎoxīn bǎ kùzi nòng zāng le.", "Tôi không cẩn thận làm bẩn quần rồi.", "Động từ"],
    ["空", "kōng", "trống, rỗng", "这个瓶子是空的，里面什么也没有。", "Zhè ge píngzi shì kōng de, lǐmiàn shénme yě méiyǒu.", "Chiếc bình này trống rỗng, bên trong chẳng có gì cả.", "Tính từ"],
    ["盒子", "hézi", "hộp, cái hộp", "这个塑料盒子里装满了新鲜水果。", "Zhè ge sùliào hézi lǐ zhuāng mǎn le xīnxiān shuǐguǒ.", "Trong chiếc hộp nhựa này đựng đầy hoa quả tươi.", "Danh từ"],
    ["扔", "rēng", "vứt, bỏ", "不要随手扔废纸。", "Bú yào suíshǒu rēng fèizhǐ.", "Đừng tiện tay vứt giấy thải.", "Động từ"],
    ["速度", "sùdù", "tốc độ", "这辆车的行驶速度非常快。", "Zhè liàng chē de xíngshǐ sùdù fēicháng kuài.", "Tốc độ di chuyển của chiếc xe này rất nhanh.", "Danh từ"],
    ["既然", "jìrán", "vì (đã... thì)", "既然来了，就多玩几天吧。", "Jìrán lái le, jiù duō wán jǐ tiān ba.", "Đã đến rồi thì ở lại chơi thêm vài ngày đi.", "Liên từ"],
    ["地球", "dìqiú", "Trái Đất", "地球是我们共同的家园。", "Dìqiú shì wǒmen gòngtóng de jiāyuán.", "Trái Đất là ngôi nhà chung của chúng ta.", "Danh từ"],
    ["停", "tíng", "dừng, đỗ", "请把车停在指定的停车位上。", "Qǐng bǎ chē tíng zài zhǐdìng de tíngchēwèi shàng.", "Xin hãy đỗ xe ở chỗ đỗ xe quy định.", "Động từ"],
    ["得意", "déyì", "đắc ý, tự hào", "取得了这么好的成绩，他感到非常得意。", "Qǔdé le zhème hǎo de chéngjì, tā gǎndào fēicháng déyì.", "Đạt được thành tích tốt như vậy, anh ấy cảm thấy rất đắc ý.", "Tính từ"],
    ["目的", "mùdì", "mục đích", "我们这次会议的主要目的是讨论新项目。", "Wǒmen zhè cì huìyì de zhǔyào mùdì shì tǎolùn xīn xiàngmù。", "Mục đích chính của cuộc họp lần này của chúng ta là thảo luận về dự án mới.", "Danh từ"],
    ["项目", "xiàngmù", "dự án, hạng mục", "这个项目需要大家共同努力才能完成。", "Zhè ge xiàngmù xūyào dàjiā gòngtóng nǔlì cái néng wánchéng.", "Dự án này cần mọi người cùng nhau nǔ lực mới có thể hoàn thành.", "Danh từ"],
    ["出错", "chūcuò", "mắc lỗi, sai sót", "做事一定要仔细，尽量避免出错。", "Zuòshì yídìng yào zǐxì, jìnliàng bìmiǎn chūcuò.", "Làm việc nhất định phải cẩn thận, cố gắng hết sức tránh mắc lỗi.", "Động từ"],
    ["塑料袋", "sùliàodài", "túi nilon, túi nhựa", "去超市买东西最好自己带购物袋，少用塑料袋。", "Qù chāoshì mǎi dōngxi zuìhǎo zìjǐ dài gòuwùdài, shǎo yòng sùliàodài.", "Đi siêu thị mua đồ tốt nhất tự mang túi mua sắm, ít dùng túi nilon.", "Danh từ"],
    ["于是", "yúshì", "thế là, cho nên", "天气太热，于是我们决定去游泳。", "Tiānqì tài rè, yúshì wǒmen juédìng qù yóuyǒng.", "Thời tiết quá nóng, thế là chúng tôi quyết định đi bơi.", "Liên từ"],
    ["鼓励", "gǔlì", "cổ vũ, khuyến khích", "老师总是鼓励我们要勇敢面对困难。", "Lǎoshī zǒngshì gǔlì wǒmen yào yǒnggǎn miànduì kùnnan.", "Thầy cô luôn khuyến khích chúng tôi phải dũng cảm đối mặt khó khăn.", "Động từ/Danh từ"],
    ["拒绝", "jùjué", "từ chối", "他礼貌地拒绝了对方的要求。", "Tā lǐmào de jùjué le duìfāng de yāoqiú.", "Anh ấy đã lịch sự từ chối yêu cầu của đối phương.", "Động từ"],
    ["减少", "jiǎnshǎo", "giảm bớt", "为了减少污染，我们要多骑自行车。", "Wèile jiǎnshǎo wūrǎn, wǒmen yào duō qí zìxíngchē.", "Để giảm bớt ô nhiễm, chúng ta nên đi xe đạp nhiều hơn.", "Động từ"],
    ["乘坐", "chéngzuò", "đi, đáp (phương tiện)", "欢迎乘坐本次列车。", "Huānyíng chéngzuò běn cì lièchē.", "Chào mừng quý khách đi chuyến tàu này.", "Động từ"],
    ["丢", "diū", "ném, vứt, mất", "我不小心把钥匙弄丢了。", "Wǒ bù xiǎoxīn bǎ yàoshi nòng diū le.", "Tôi không cẩn thận làm mất chìa khóa rồi.", "Động từ"],
    ["垃圾桶", "lājītǒng", "thùng rác", "请把废纸扔进垃圾桶。", "Qǐng bǎ fèizhǐ rēng jìn lājītǒng.", "Xin hãy vứt giấy thải vào thùng rác.", "Danh từ"],
    ["美丽", "měilì", "đẹp, xinh đẹp", "这里的风景非常美丽。", "Zhèlǐ de fēngjǐng fēicháng měilì.", "Phong cảnh ở đây rất xinh đẹp.", "Tính từ"]
],
 "hsk15": [
    ["弹钢琴", "tán gāngqín", "chơi đàn dương cầm", "她每天都练习弹钢琴。", "Tā měitiān dōu liànxí tán gāngqín.", "Cô ấy mỗi ngày đều luyện tập chơi piano.", "Cụm động từ"],
    ["棒", "bàng", "xuất sắc", "你的表现真棒！", "Nǐ de biǎoxiàn zhēn bàng!", "Biểu hiện của bạn thật xuất sắc!", "Tính từ"],
    ["孙子", "sūnzi", "cháu nội trai", "他很疼爱自己的孙子。", "Tā hěn téng'ài zìjǐ de sūnzi.", "Ông ấy rất yêu thương cháu trai của mình.", "Danh từ"],
    ["孙女", "sūnnǚ", "cháu nội gái", "她有一个可爱的孙女。", "Tā yǒu yí ge kě'ài de sūnnǚ.", "Bà ấy có một người cháu gái dễ thương.", "Danh từ"],
    ["寒假", "hánjià", "kỳ nghỉ đông", "寒假你打算去哪儿玩？", "Hánjià nǐ dǎsuàn qù nǎr wán?", "Kỳ nghỉ đông bạn định đi đâu chơi?", "Danh từ"],
    ["暑假", "shǔjià", "nghỉ hè", "暑假快到了。", "Shǔjià kuài dào le.", "Kỳ nghỉ hè sắp đến rồi.", "Danh từ"],
    ["放暑假", "fàng shǔjià", "nghỉ hè", "七月份我们就要放暑假了。", "Qī yuèfèn wǒmen jiù yào fàng shǔjià le.", "Tháng 7 chúng tôi sẽ được nghỉ hè rồi.", "Cụm động từ"],
    ["父亲", "fùqīn", "cha, bố", "他的父亲是一位医生。", "Tā de fùqīn shì yí wèi yīshēng.", "Cha của anh ấy là một bác sĩ.", "Danh từ"],
    ["母亲", "mǔqīn", "mẫu thân", "我的母亲是一位老师。", "Wǒ de mǔqīn shì yí wèi lǎoshī.", "Mẹ của tôi là một giáo viên.", "Danh từ"],
    ["闹钟", "nàozhōng", "đồng hồ báo thức", "我定了一个七点的闹钟。", "Wǒ dìng le yí ge qī diǎn de nàozhōng.", "Tôi đã đặt một chiếc đồng hồ báo thức lúc 7 giờ.", "Danh từ"],
    ["响", "xiǎng", "kêu, reo, vang", "电话响了。", "Diànhuà xiǎng le.", "Điện thoại reo rồi.", "Động từ"],
    ["醒", "xǐng", "thức dậy", "他还没醒。", "Tā hái méi xǐng.", "Anh ấy vẫn chưa thức dậy.", "Động từ"],
    ["赶", "gǎn", "vội, gấp", "他正在赶去机场。", "Tā zhèngzài gǎn qù jīchǎng.", "Anh ấy đang vội ra sân bay.", "Động từ"],
    ["厕所", "cèsuǒ", "nhà wc", "请问厕所在哪里？", "Qǐngwèn cèsuǒ zài nǎlǐ?", "Xin hỏi nhà vệ sinh ở đâu?", "Danh từ"],
    ["批评", "pīpíng", "phê bình", "经理批评了他。", "Jīnglǐ pīpíng le tā.", "Giám đốc đã phê bình anh ấy.", "Động từ"],
    ["弄", "nòng", "làm, kiếm", "别把衣服弄脏了。", "Bié bǎ yīfu nòng zāng le.", "Đừng làm bẩn quần áo.", "Động từ"],
    ["管理", "guǎnlǐ", "quản lý", "他管理公司管理得很好。", "Tā guǎnlǐ gōngsī guǎnlǐ de hěn hǎo.", "Anh ấy quản lý công ty rất tốt.", "Động/Danh từ"],
    ["打针", "dǎzhēn", "tiêm", "小孩子害怕打针。", "Xiǎoháizi hàipà dǎzhēn.", "Trẻ em sợ tiêm thuốc.", "Động từ"],
    ["护士", "hùshi", "y tá", "她是一名护士。", "Tā shì yì míng hùshi.", "Cô ấy là một y tá.", "Danh từ"],
    ["错误", "cuòwù", "lỗi", "他承认了自己的错误。", "Tā chéngrèn le zìjǐ de cuòwù.", "Anh ấy đã thừa nhận lỗi lầm của mình.", "Danh/Tính từ"],
    ["犯", "fàn", "phạm", "千万别再犯错了。", "Qiānwàn bié zài fàncuò le.", "Nhất thiết đừng phạm lỗi nữa.", "Động từ"],
    ["听取", "tīngqǔ", "lắng nghe", "我们要多听取别人的意见。", "Wǒmen yào duō tīngqǔ biérén de yìjiàn.", "Chúng ta cần lắng nghe nhiều hơn ý kiến của người khác.", "Động từ"],
    ["操作", "cāozuò", "thao tác", "这个操作很简单。", "Zhège cāozuò hěn jiǎndān.", "Thao tác này rất đơn giản.", "Động/Danh từ"],
    ["系统", "xìtǒng", "hệ thống", "电脑系统需要更新。", "Diànnǎo xìtǒng xūyào gēngxīn.", "Hệ thống máy tính cần được cập nhật.", "Danh từ"],
    ["设备", "shèbèi", "thiết bị", "这家医院的设备很先进。", "Zhè jiā yīyuàn de shèbèi hěn xiānjìn.", "Thiết bị của bệnh viện này rất tiên tiến.", "Danh từ"],
    ["统计", "tǒngjì", "thống kê", "请把这个月的数据统计一下。", "Qǐng bǎ zhège yuè de shùjù tǒngjì yíxià.", "Xin hãy thống kê lại dữ liệu của tháng này.", "Động từ"],
    ["数据", "shùjù", "số liệu", "这些数据非常重要。", "Zhèxiē shùjù fēicháng zhòngyào.", "Những số liệu này vô cùng quan trọng.", "Danh từ"],
    ["表扬", "biǎoyáng", "biểu dương", "老师表扬了他。", "Lǎoshī biǎoyáng le tā.", "Giáo viên đã biểu dương anh ấy.", "Động từ"],
    ["千万", "qiānwàn", "nhất thiết phải", "千万别去！", "Qiānwàn bié qù!", "Tuyệt đối đừng đi!", "Phó từ"],
    ["怀疑", "huáiyí", "hoài nghi", "我怀疑他说谎。", "Wǒ huáiyí tā shuōhuǎng.", "Tôi hoài nghi anh ta nói dối.", "Động từ"],
    ["故意", "gùyì", "cố ý", "对不起，我不是故意的。", "Duìbùqǐ, wǒ bú shì gùyì de.", "Xin lỗi, tôi không cố ý.", "Phó từ"],
    ["敲", "qiāo", "gõ", "有人在敲门。", "Yǒurén zài qiāo mén.", "Có người đang gõ cửa.", "Động từ"],
    ["整理", "zhěnglǐ", "dọn dẹp, sắp xếp", "请整理一下房间。", "Qǐng zhěnglǐ yíxià fángjiān.", "Hãy dọn dẹp lại phòng một chút.", "Động từ"],
    ["合适", "héshì", "thích hợp", "这件衣服很合适。", "Zhè jiàn yīfu hěn héshì.", "Bộ quần áo này rất vừa vặn.", "Tính từ"],
    ["骗", "piàn", "lừa gạt", "你千万别骗我。", "Nǐ qiānwàn bié piàn wǒ.", "Tuyệt đối đừng lừa tôi.", "Động từ"],
    ["儿童", "értóng", "trẻ em", "这是给儿童看的书。", "Zhè shì gěi értóng kàn de shū.", "Đây là sách dành cho trẻ em đọc.", "Danh từ"],
    ["假", "jiǎ", "giả", "这个消息是假的。", "Zhège xiāoxi shì jiǎ de.", "Tin tức này là giả đấy.", "Tính từ"],
    ["左右", "zuǒyòu", "khoảng", "明天下午三点左右。", "Míngtiān xiàwǔ sān diǎn zuǒyòu.", "Khoảng 3 giờ chiều mai.", "Danh từ"],
    ["懒", "lǎn", "lười biếng", "他有点儿懒。", "Tā yǒudiǎnr lǎn.", "Cậu ấy hơi lười một chút.", "Tính từ"],
    ["笨", "bèn", "ngốc, vụng về", "我太笨了。", "Wǒ tài bèn le.", "Tôi ngốc quá.", "Tính từ"],
    ["粗心", "cūxīn", "cẩu thả, sơ ý", "考试时不能粗心。", "Kǎoshì shí bùnéng cūxīn.", "Khi thi không được cẩu thả.", "Tính từ"],
    ["骄傲", "jiāo'ào", "tự hào, kiêu ngạo", "父母为你感到骄傲。", "Fùmǔ wèi nǐ gǎndào jiāo'ào.", "Bố mẹ cảm thấy tự hào về bạn.", "Tính từ"],
    ["害羞", "hàixiū", "xấu hổ", "那个女孩很害羞。", "Nàge nǚhái hěn hàixiū.", "Cô bé đó rất e thẹn.", "Tính từ"]
],
  "hsk16": [
    ["故意", "gùyì", "cố ý", "对不起，我不是故意的。", "Duìbùqǐ, wǒ bú shì gùyì de.", "Xin lỗi, tôi không phải cố ý đâu.", "Phó từ"],
    ["观众", "guānzhòng", "khán giả", "现场有很多观众。", "Xiànchǎng yǒu hěn duō guānzhòng.", "Tại hiện trường có rất nhiều khán giả.", "Danh từ"],
    ["管理", "guǎnlǐ", "quản lý", "他学的是企业管理专业。", "Tā xué de shì qǐyè guǎnlǐ zhuānyè.", "Anh ấy học chuyên ngành quản trị doanh nghiệp.", "Động từ/Danh từ"],
    ["规定", "guīdìng", "quy định", "根据公司规定，不能迟到。", "Gēnjù gōngsī guīdìng, bù néng chídào.", "Theo quy định của công ty, không được đến muộn.", "Danh từ/Động từ"],
    ["国籍", "guójí", "quốc tịch", "请问您的国籍是什么？", "Qǐngwèn nín de guójí shì shénme?", "Xin hỏi quốc tịch của ngài là gì?", "Danh từ"],
    ["果汁", "guǒzhī", "nước ép hoa quả", "我想喝一杯苹果汁。", "Wǒ xiǎng hē yì bēi píngguǒ zhī.", "Tôi muốn uống một cốc nước ép táo.", "Danh từ"],
    ["海洋", "hǎiyáng", "đại dương", "海洋里有很多种鱼。", "Hǎiyáng lǐ yǒu hěn duō zhǒng yú.", "Trong đại dương có rất nhiều loại cá.", "Danh từ"],
    ["害羞", "hàixiū", "xấu hổ, ngại ngùng", "那个小女孩很害羞。", "Nàge xiǎo nǚhái hěn hàixiū.", "Cô bé đó rất hay xấu hổ.", "Tính từ"],
    ["寒假", "hánjià", "kỳ nghỉ đông", "我们一月份开始放寒假。", "Wǒmen yī yuèfèn kāishǐ fàng hánjià.", "Chúng tôi bắt đầu nghỉ đông từ tháng 1.", "Danh từ"],
    ["号码", "hàomǎ", "số (điện thoại, phòng...)", "请留一下您的电话号码。", "Qǐng liú yíxià nín de diànhuà hàomǎ.", "Xin hãy để lại số điện thoại của ngài.", "Danh từ"],
    ["合格", "hégé", "đạt tiêu chuẩn, hợp quy cách", "这些产品都是合格的。", "Zhèxiē chǎnpǐn dōu shì hégé de.", "Những sản phẩm này đều đạt tiêu chuẩn.", "Tính từ"],
    ["合适", "héshì", "phù hợp", "这双鞋你穿很合适。", "Zhè shuāng xié nǐ chuān hěn héshì.", "Đôi giày này bạn đi rất phù hợp.", "Tính từ"],
    ["盒子", "hézi", "cái hộp", "这个盒子里装的是什么？", "Zhège hézi lǐ zhuāng de shì shénme?", "Trong cái hộp này đựng cái gì vậy?", "Danh từ"],
    ["厚", "hòu", "dày", "这本字典很厚。", "Zhè běn zìdiǎn hěn hòu.", "Cuốn từ điển này rất dày.", "Tính từ"],
    ["互联网", "hùliánwǎng", "internet", "互联网改变了我们的生活。", "Hùliánwǎng gǎibiàn le wǒmen de shēnghuó.", "Internet đã làm thay đổi cuộc sống của chúng ta.", "Danh từ"],
    ["护士", "hùshi", "y tá", "她在医院当护士。", "Tā zài yīyuàn dāng hùshi.", "Cô ấy làm y tá trong bệnh viện.", "Danh từ"],
    ["怀疑", "huáiyí", "nghi ngờ", "警察怀疑是他偷的。", "Jǐngchá huáiyí shì tā tōu de.", "Cảnh sát nghi ngờ là anh ta trộm.", "Động từ"],
    ["活泼", "huópō", "hoạt bát", "这个孩子性格很活泼。", "Zhège háizi xìnggé hěn huópō.", "Tính cách đứa bé này rất hoạt bát.", "Tính từ"],
    ["火", "huǒ", "lửa, hot (nổi tiếng)", "这家饭店现在很火。", "Zhè jiā fàndiàn xiànzài hěn huǒ.", "Nhà hàng này bây giờ đang rất hot.", "Danh từ/Tính từ"],
    ["激动", "jīdòng", "kích động, xúc động", "听到好消息，他激动得哭了。", "Tīngdào hǎo xiāoxi, tā jīdòng de kū le.", "Nghe được tin tốt, anh ấy xúc động đến khóc.", "Tính từ"],
    ["记者", "jìzhě", "phóng viên, nhà báo", "有很多记者在采访他。", "Yǒu hěn duō jìzhě zài cǎifǎng tā.", "Có rất nhiều phóng viên đang phỏng vấn anh ấy.", "Danh từ"],
    ["技术", "jìshù", "kỹ thuật", "他们的电脑技术很好。", "Tāmen de diànnǎo jìshù hěn hǎo.", "Kỹ thuật máy tính của họ rất tốt.", "Danh từ"],
    ["继续", "jìxù", "tiếp tục", "休息十分钟后，我们继续上课。", "Xiūxi shí fēnzhōng hòu, wǒmen jìxù shàngkè.", "Sau 10 phút nghỉ giải lao, chúng ta tiếp tục học.", "Động từ"],
    ["加油站", "jiāyóuzhàn", "trạm xăng", "前面有个加油站，我们去加油吧。", "Qiánmiàn yǒu ge jiāyóuzhàn, wǒmen qù jiāyóu ba.", "Phía trước có một trạm xăng, chúng ta đi đổ xăng nhé.", "Danh từ"],
    ["假", "jiǎ", "giả", "他说的话是假的。", "Tā shuō de huà shì jiǎ de.", "Lời anh ta nói là giả đấy.", "Tính từ"]
  ],
  "hsk17": [
    ["饺子", "jiǎozi", "sủi cảo", "过年时我们都要吃饺子。", "Guònián shí wǒmen dōu yào chī jiǎozi.", "Khi ăn tết chúng tôi đều phải ăn sủi cảo.", "Danh từ"],
    ["接着", "jiēzhe", "tiếp theo, liền theo", "他喝了一口水，接着说。", "Tā hē le yì kǒu shuǐ, jiēzhe shuō.", "Anh ấy uống một ngụm nước, rồi nói tiếp.", "Phó từ"],
    ["节", "jié", "tiết học, ngày lễ", "今天上午我有三节课。", "Jīntiān shàngwǔ wǒ yǒu sān jié kè.", "Sáng nay tôi có ba tiết học.", "Lượng từ/Danh từ"],
    ["进行", "jìnxíng", "tiến hành", "会议正在进行中。", "Huìyì zhèngzài jìnxíng zhōng.", "Cuộc họp đang được tiến hành.", "Động từ"],
    ["禁止", "jìnzhǐ", "cấm", "这里禁止停车。", "Zhèlǐ jìnzhǐ tíngchē.", "Ở đây cấm đỗ xe.", "Động từ"],
    ["京剧", "jīngjù", "kinh kịch", "我爷爷很喜欢看京剧。", "Wǒ yéye hěn xǐhuan kàn jīngjù.", "Ông nội tôi rất thích xem kinh kịch.", "Danh từ"],
    ["精彩", "jīngcǎi", "đặc sắc, xuất sắc", "这场足球比赛非常精彩。", "Zhè chǎng zúqiú bǐsài fēicháng jīngcǎi.", "Trận đấu bóng đá này vô cùng đặc sắc.", "Tính từ"],
    ["竞争", "jìngzhēng", "cạnh tranh", "现在的商业竞争很激烈。", "Xiànzài de shāngyè jìngzhēng hěn jīliè.", "Cạnh tranh thương mại hiện nay rất khốc liệt.", "Động từ/Danh từ"],
    ["究竟", "jiūjìng", "rốt cuộc", "你究竟想说什么？", "Nǐ jiūjìng xiǎng shuō shénme?", "Rốt cuộc là bạn muốn nói cái gì?", "Phó từ"],
    ["举", "jǔ", "giơ, nâng", "有问题请举手。", "Yǒu wèntí qǐng jǔ shǒu.", "Có câu hỏi xin hãy giơ tay.", "Động từ"],
    ["开心", "kāixīn", "vui vẻ", "今天玩得真开心！", "Jīntiān wán de zhēn kāixīn!", "Hôm nay chơi thật là vui vẻ!", "Tính từ"],
    ["看法", "kànfǎ", "cách nhìn, quan điểm", "你对这件事有什么看法？", "Nǐ duì zhè jiàn shì yǒu shénme kànfǎ?", "Bạn có cách nhìn gì về việc này?", "Danh từ"],
    ["棵", "kē", "cây (lượng từ)", "院子里种着一棵苹果树。", "Yuànzi lǐ zhòng zhe yì kē píngguǒ shù.", "Trong sân trồng một cây táo.", "Lượng từ"],
    ["咳嗽", "késou", "ho", "他感冒了，一直咳嗽。", "Tā gǎnmào le, yìzhí késou.", "Anh ấy bị cảm, ho suốt.", "Động từ"],
    ["可怜", "kělián", "đáng thương", "那只流浪狗真可怜。", "Nà zhǐ liúlàng gǒu zhēn kělián.", "Con chó hoang đó thật đáng thương.", "Tính từ"],
    ["客厅", "kètīng", "phòng khách", "客人们正在客厅里聊天。", "Kèrén men zhèngzài kètīng lǐ liáotiān.", "Các vị khách đang trò chuyện trong phòng khách.", "Danh từ"],
    ["空", "kōng", "trống, không", "这个箱子是空的。", "Zhège xiāngzi shì kōng de.", "Cái rương này là trống rỗng.", "Tính từ"],
    ["恐怕", "kǒngpà", "e rằng, sợ rằng", "时间不早了，我恐怕得走了。", "Shíjiān bù zǎo le, wǒ kǒngpà děi zǒu le.", "Thời gian không còn sớm, e rằng tôi phải đi rồi.", "Phó từ"],
    ["苦", "kǔ", "đắng", "这药太苦了。", "Zhè yào tài kǔ le.", "Thuốc này đắng quá.", "Tính từ"],
    ["矿泉水", "kuàngquánshuǐ", "nước khoáng, nước suối", "请给我一瓶矿泉水。", "Qǐng gěi wǒ yì píng kuàngquánshuǐ.", "Xin cho tôi một chai nước suối.", "Danh từ"],
    ["垃圾桶", "lājītǒng", "thùng rác", "请把垃圾扔进垃圾桶里。", "Qǐng bǎ lājī rēng jìn lājītǒng lǐ.", "Xin hãy vứt rác vào trong thùng rác.", "Danh từ"],
    ["辣", "là", "cay", "这个菜太辣了，我吃不下。", "Zhège cài tài là le, wǒ chī bú xià.", "Món này cay quá, tôi ăn không nổi.", "Tính từ"],
    ["来得及", "láidejí", "kịp", "现在去火车站还来得及。", "Xiànzài qù huǒchēzhàn hái láidejí.", "Bây giờ đi ga tàu vẫn còn kịp.", "Động từ"],
    ["来自", "láizì", "đến từ", "这些学生来自不同的国家。", "Zhèxiē xuéshēng láizì bùtóng de guójiā.", "Những sinh viên này đến từ các quốc gia khác nhau.", "Động từ"],
    ["懒", "lǎn", "lười biếng", "他很懒，什么家务都不做。", "Tā hěn lǎn, shénme jiāwù dōu bú zuò.", "Anh ấy rất lười, chẳng làm việc nhà gì cả.", "Tính từ"]
  ],
  "hsk18": [
    ["老虎", "lǎohǔ", "con hổ", "动物园里有两只老虎。", "Dòngwùyuán lǐ yǒu liǎng zhǐ lǎohǔ.", "Trong sở thú có hai con hổ.", "Danh từ"],
    ["冷静", "lěngjìng", "bình tĩnh", "遇到危险时要保持冷静。", "Yùdào wēixiǎn shí yào bǎochí lěngjìng.", "Khi gặp nguy hiểm phải giữ bình tĩnh.", "Tính từ"],
    ["离婚", "líhūn", "ly hôn", "他们因为性格不合离婚了。", "Tāmen yīnwèi xìnggé bù hé líhūn le.", "Họ vì tính cách không hợp nên đã ly hôn.", "Động từ"],
    ["礼貌", "lǐmào", "lễ phép", "这个孩子非常有礼貌。", "Zhège háizi fēicháng yǒu lǐmào.", "Đứa bé này vô cùng lễ phép.", "Danh từ/Tính từ"],
    ["理发", "lǐfà", "cắt tóc", "你的头发太长了，该去理发了。", "Nǐ de tóufa tài cháng le, gāi qù lǐfà le.", "Tóc của bạn dài quá rồi, nên đi cắt tóc đi.", "Động từ"],
    ["厉害", "lìhai", "lợi hại, nghiêm trọng", "他病得很厉害。", "Tā bìng de hěn lìhai.", "Anh ấy ốm rất nghiêm trọng.", "Tính từ"],
    ["连", "lián", "ngay cả", "他太忙了，连吃饭的时间都没有。", "Tā tài máng le, lián chīfàn de shíjiān dōu méiyǒu.", "Anh ấy bận quá, ngay cả thời gian ăn cơm cũng không có.", "Giới từ"],
    ["零钱", "língqián", "tiền lẻ", "你身上有零钱吗？", "Nǐ shēnshang yǒu língqián ma?", "Trên người bạn có tiền lẻ không?", "Danh từ"],
    ["流泪", "liúlèi", "rơi nước mắt", "听到这个故事，她忍不住流泪了。", "Tīngdào zhège gùshi, tā rěnbuzhù liúlèi le.", "Nghe câu chuyện này, cô ấy không kiềm được rơi nước mắt.", "Động từ"],
    ["流利", "liúlì", "lưu loát", "他的汉语说得很流利。", "Tā de Hànyǔ shuō de hěn liúlì.", "Tiếng Trung của anh ấy nói rất lưu loát.", "Tính từ"],
    ["旅行", "lǚxíng", "du lịch", "我们计划明年去欧洲旅行。", "Wǒmen jìhuà míngnián qù Ōuzhōu lǚxíng.", "Chúng tôi lên kế hoạch sang năm đi Châu Âu du lịch.", "Động từ/Danh từ"],
    ["马虎", "mǎhu", "cẩu thả, qua loa", "做事情不能太马虎。", "Zuò shìqing bù néng tài mǎhu.", "Làm việc không thể quá cẩu thả.", "Tính từ"],
    ["毛", "máo", "lông, hào (tiền tệ)", "这只猫的毛很白。", "Zhè zhǐ māo de máo hěn bái.", "Lông của con mèo này rất trắng.", "Danh từ/Lượng từ"],
    ["毛巾", "máojīn", "khăn mặt", "请帮我拿一条毛巾来。", "Qǐng bāng wǒ ná yì tiáo máojīn lái.", "Xin hãy giúp tôi lấy một chiếc khăn mặt đến đây.", "Danh từ"],
    ["美丽", "měilì", "xinh đẹp", "这里的风景非常美丽。", "Zhèlǐ de fēngjǐng fēicháng měilì.", "Phong cảnh ở đây vô cùng xinh đẹp.", "Tính từ"],
    ["梦", "mèng", "giấc mơ", "昨晚我做了一个奇怪的梦。", "Zuówǎn wǒ zuò le yí ge qíguài de mèng.", "Đêm qua tôi đã có một giấc mơ kỳ lạ.", "Danh từ"],
    ["秒", "miǎo", "giây", "他跑一百米只需要十秒。", "Tā pǎo yì bǎi mǐ zhǐ xūyào shí miǎo.", "Anh ấy chạy 100m chỉ cần 10 giây.", "Lượng từ"],
    ["民族", "mínzú", "dân tộc", "中国有五十六个民族。", "Zhōngguó yǒu wǔshíliù ge mínzú.", "Trung Quốc có 56 dân tộc.", "Danh từ"],
    ["目的", "mùdì", "mục đích", "你这样做的目的是什么？", "Nǐ zhèyàng zuò de mùdì shì shénme?", "Mục đích bạn làm như vậy là gì?", "Danh từ"],
    ["难受", "nánshòu", "khó chịu", "我感冒了，身体很难受。", "Wǒ gǎnmào le, shēntǐ hěn nánshòu.", "Tôi bị cảm, cơ thể rất khó chịu.", "Tính từ"],
    ["内容", "nèiróng", "nội dung", "这篇文章的内容很丰富。", "Zhè piān wénzhāng de nèiróng hěn fēngfù.", "Nội dung của bài văn này rất phong phú.", "Danh từ"],
    ["弄", "nòng", "làm, nghịch", "对不起，我把你的衣服弄脏了。", "Duìbùqǐ, wǒ bǎ nǐ de yīfu nòng zāng le.", "Xin lỗi, tôi làm bẩn quần áo của bạn rồi.", "Động từ"],
    ["排队", "páiduì", "xếp hàng", "买票的人很多，需要排队。", "Mǎi piào de rén hěn duō, xūyào páiduì.", "Người mua vé rất đông, cần phải xếp hàng.", "Động từ"],
    ["排列", "páiliè", "sắp xếp", "请把这些书按顺序排列好。", "Qǐng bǎ zhèxiē shū àn shùnxù páiliè hǎo.", "Xin hãy sắp xếp những quyển sách này theo thứ tự.", "Động từ"],
    ["批评", "pīpíng", "phê bình", "老师批评了他。", "Lǎoshī pīpíng le tā.", "Giáo viên đã phê bình anh ấy.", "Động từ"]
  ],
  "hsk19": [
    ["骗", "piàn", "lừa gạt", "你别骗我了。", "Nǐ bié piàn wǒ le.", "Bạn đừng lừa tôi nữa.", "Động từ"],
    ["乒乓球", "pīngpāngqiú", "bóng bàn", "下午我们去打乒乓球吧。", "Xiàwǔ wǒmen qù dǎ pīngpāngqiú ba.", "Chiều nay chúng ta đi đánh bóng bàn nhé.", "Danh từ"],
    ["破", "pò", "rách, vỡ", "我的杯子破了。", "Wǒ de bēizi pò le.", "Cái cốc của tôi vỡ rồi.", "Tính từ/Động từ"],
    ["千万", "qiānwàn", "nhất thiết, bằng mọi giá", "你千万别告诉别人。", "Nǐ qiānwàn bié gàosu biérén.", "Bạn nhất thiết đừng nói cho người khác biết.", "Phó từ"],
    ["敲", "qiāo", "gõ", "有人在敲门。", "Yǒurén zài qiāo mén.", "Có người đang gõ cửa.", "Động từ"],
    ["桥", "qiáo", "cây cầu", "河上有一座石桥。", "Hé shàng yǒu yí zuò shíqiáo.", "Trên sông có một cây cầu đá.", "Danh từ"],
    ["请客", "qǐngkè", "mời khách, đãi", "今天发工资了，我请客！", "Jīntiān fā gōngzī le, wǒ qǐngkè!", "Hôm nay phát lương rồi, tôi mời!", "Động từ"],
    ["然而", "rán'ér", "tuy nhiên, nhưng", "他虽然失败了，然而并没有放弃。", "Tā suīrán shībài le, rán'ér bìng méiyǒu fàngqì.", "Mặc dù anh ấy thất bại, tuy nhiên không hề từ bỏ.", "Liên từ"],
    ["让", "ràng", "nhường, bảo, để", "请让一下，我要过去。", "Qǐng ràng yíxià, wǒ yào guòqù.", "Xin nhường một chút, tôi muốn đi qua.", "Động từ"],
    ["热闹", "rènao", "náo nhiệt", "过年时街上非常热闹。", "Guònián shí jiē shàng fēicháng rènao.", "Lúc đón tết trên phố vô cùng náo nhiệt.", "Tính từ"],
    ["扔", "rēng", "ném, vứt", "请把垃圾扔掉。", "Qǐng bǎ lājī rēng diào.", "Xin hãy vứt rác đi.", "Động từ"],
    ["仍然", "réngrán", "vẫn", "虽然下雨，他仍然坚持去跑步。", "Suīrán xiàyǔ, tā réngrán jiānchí qù pǎobù.", "Mặc dù trời mưa, anh ấy vẫn kiên trì đi chạy bộ.", "Phó từ"],
    ["日记", "rìjì", "nhật ký", "她每天都有写日记的习惯。", "Tā měitiān dōu yǒu xiě rìjì de xíguàn.", "Cô ấy mỗi ngày đều có thói quen viết nhật ký.", "Danh từ"],
    ["软", "ruǎn", "mềm", "这块蛋糕很软。", "Zhè kuài dàngāo hěn ruǎn.", "Miếng bánh kem này rất mềm.", "Tính từ"],
    ["森林", "sēnlín", "rừng rậm", "这片森林里有很多动物。", "Zhè piàn sēnlín lǐ yǒu hěn duō dòngwù.", "Trong khu rừng này có rất nhiều động vật.", "Danh từ"],
    ["社会", "shèhuì", "xã hội", "我们要适应社会的发展。", "Wǒmen yào shìyìng shèhuì de fāzhǎn.", "Chúng ta phải thích nghi với sự phát triển của xã hội.", "Danh từ"],
    ["申请", "shēnqǐng", "xin, đăng ký", "我准备申请一份新工作。", "Wǒ zhǔnbèi shēnqǐng yí fèn xīn gōngzuò.", "Tôi chuẩn bị xin một công việc mới.", "Động từ"],
    ["省", "shěng", "tỉnh, tiết kiệm", "坐地铁能省很多时间。", "Zuò dìtiě néng shěng hěn duō shíjiān.", "Đi tàu điện ngầm có thể tiết kiệm rất nhiều thời gian.", "Danh từ/Động từ"],
    ["剩", "shèng", "thừa lại", "饭菜还剩很多。", "Fàncài hái shèng hěn duō.", "Cơm canh vẫn còn thừa lại rất nhiều.", "Động từ"],
    ["失望", "shīwàng", "thất vọng", "他的表现让我很失望。", "Tā de biǎoxiàn ràng wǒ hěn shīwàng.", "Sự thể hiện của anh ấy làm tôi rất thất vọng.", "Tính từ"],
    ["十分", "shífēn", "mười phần, vô cùng", "我对这个结果十分满意。", "Wǒ duì zhège jiéguǒ shífēn mǎnyì.", "Tôi vô cùng hài lòng với kết quả này.", "Phó từ"],
    ["实际", "shíjì", "thực tế", "理论必须联系实际。", "Lǐlùn bìxū liánxì shíjì.", "Lý luận bắt buộc phải liên hệ với thực tế.", "Danh từ/Tính từ"],
    ["实在", "shízài", "thực sự", "他实在太累了。", "Tā shízài tài lèi le.", "Anh ấy thực sự quá mệt rồi.", "Phó từ"],
    ["世纪", "shìjì", "thế kỷ", "我们生活在21世纪。", "Wǒmen shēnghuó zài 21 shìjì.", "Chúng ta sống ở thế kỷ 21.", "Danh từ"],
    ["是否", "shìfǒu", "có hay không", "你是否同意我的看法？", "Nǐ shìfǒu tóngyì wǒ de kànfǎ?", "Bạn có đồng ý với cách nhìn của tôi không?", "Phó từ"]
  ],
  "hsk20": [
    ["收", "shōu", "thu, nhận", "我已经收到了你的信。", "Wǒ yǐjīng shōu dào le nǐ de xìn.", "Tôi đã nhận được thư của bạn rồi.", "Động từ"],
    ["收拾", "shōushi", "dọn dẹp", "请把桌子收拾一下。", "Qǐng bǎ zhuōzi shōushi yíxià.", "Xin hãy dọn dẹp bàn một chút.", "Động từ"],
    ["受不了", "shòubuliǎo", "chịu không nổi", "这里的天气太热了，我受不了。", "Zhèlǐ de tiānqì tài rè le, wǒ shòubuliǎo.", "Thời tiết ở đây nóng quá, tôi chịu không nổi.", "Cụm động từ"],
    ["输", "shū", "thua", "这场比赛我们输了。", "Zhè chǎng bǐsài wǒmen shū le.", "Trận đấu này chúng tôi thua rồi.", "Động từ"],
    ["数量", "shùliàng", "số lượng", "这种产品的数量有限。", "Zhè zhǒng chǎnpǐn de shùliàng yǒuxiàn.", "Số lượng của sản phẩm này có hạn.", "Danh từ"],
    ["速度", "sùdù", "tốc độ", "他开车的速度很快。", "Tā kāichē de sùdù hěn kuài.", "Tốc độ lái xe của anh ấy rất nhanh.", "Danh từ"],
    ["酸", "suān", "chua", "这个苹果太酸了。", "Zhège píngguǒ tài suān le.", "Quả táo này chua quá.", "Tính từ"],
    ["孙子", "sūnzi", "cháu nội", "爷爷很疼爱他的小孙子。", "Yéye hěn téng'ài tā de xiǎo sūnzi.", "Ông nội rất thương yêu đứa cháu nội nhỏ của mình.", "Danh từ"],
    ["抬", "tái", "khiêng, nâng", "把头抬起来。", "Bǎ tóu tái qǐlái.", "Nâng đầu lên.", "Động từ"],
    ["弹钢琴", "tán gāngqín", "đánh piano", "她的爱好是弹钢琴。", "Tā de àihào shì tán gāngqín.", "Sở thích của cô ấy là đánh piano.", "Cụm động từ"],
    ["汤", "tāng", "canh", "这碗汤真好喝。", "Zhè wǎn tāng zhēn hǎohē.", "Bát canh này thật sự rất ngon.", "Danh từ"],
    ["趟", "tàng", "chuyến (lượng từ đi lại)", "我明天要去一趟北京。", "Wǒ míngtiān yào qù yí tàng Běijīng.", "Ngày mai tôi phải đi một chuyến Bắc Kinh.", "Lượng từ"],
    ["同情", "tóngqíng", "đồng tình, thông cảm", "我很同情他的遭遇。", "Wǒ hěn tóngqíng tā de zāoyù.", "Tôi rất thông cảm với hoàn cảnh của anh ấy.", "Động từ/Danh từ"],
    ["推", "tuī", "đẩy", "请把门推开。", "Qǐng bǎ mén tuī kāi.", "Xin hãy đẩy cửa ra.", "Động từ"],
    ["脱", "tuō", "cởi (quần áo, giày)", "太热了，我把外套脱了。", "Tài rè le, wǒ bǎ wàitào tuō le.", "Nóng quá, tôi cởi áo khoác ra rồi.", "Động từ"],
    ["网站", "wǎngzhàn", "trang web", "这是一个学习汉语的网站。", "Zhè shì yí ge xuéxí Hànyǔ de wǎngzhàn.", "Đây là một trang web học tiếng Hán.", "Danh từ"],
    ["往", "wǎng", "hướng về", "一直往前走就到了。", "Yìzhí wǎng qián zǒu jiù dào le.", "Cứ đi thẳng về phía trước là tới.", "Giới từ"],
    ["卫生间", "wèishēngjiān", "nhà vệ sinh", "请问卫生间在哪里？", "Qǐngwèn wèishēngjiān zài nǎlǐ?", "Xin hỏi nhà vệ sinh ở đâu?", "Danh từ"],
    ["温度", "wēndù", "nhiệt độ", "今天室外的温度是30度。", "Jīntiān shìwài de wēndù shì 30 dù.", "Nhiệt độ ngoài trời hôm nay là 30 độ.", "Danh từ"],
    ["文章", "wénzhāng", "bài văn", "这篇文章写得很好。", "Zhè piān wénzhāng xiě de hěn hǎo.", "Bài văn này viết rất hay.", "Danh từ"],
    ["咸", "xián", "mặn", "这个汤太咸了。", "Zhège tāng tài xián le.", "Canh này mặn quá.", "Tính từ"],
    ["相同", "xiāngtóng", "giống nhau", "我们俩的看法完全相同。", "Wǒmen liǎ de kànfǎ wánquán xiāngtóng.", "Cách nhìn của hai chúng tôi hoàn toàn giống nhau.", "Tính từ"],
    ["香", "xiāng", "thơm", "这朵花真香。", "Zhè duǒ huā zhēn xiāng.", "Bông hoa này thật thơm.", "Tính từ"],
    ["详细", "xiángxì", "chi tiết", "请把经过详细地说一遍。", "Qǐng bǎ jīngguò xiángxì de shuō yí biàn.", "Xin hãy nói lại chi tiết quá trình.", "Tính từ"],
    ["响", "xiǎng", "kêu, vang", "你的手机响了。", "Nǐ de shǒujī xiǎng le.", "Điện thoại của bạn kêu kìa.", "Động từ"]
  ]
};

const HSK_DATA = Object.fromEntries(Object.entries(_HSK_RAW).map( ([k,v]) => [k, v.map( ([hanzi,pinyin,meaning,ex_hanzi,ex_pinyin,ex_viet,tu_loai]) => ({
    hanzi,
    pinyin,
    meaning,
    ex_hanzi,
    ex_pinyin,
    ex_viet,
    tu_loai
}))]));

if (typeof module !== "undefined")
    module.exports = {
        HSK_DATA
    };
